#!/usr/bin/env python3
"""Read-only export of the B-LF r1 slots that E5 reuses as its FULL arm (gate G4).

The final-batch ledger lives outside the repository and is not linkable from it. This
script is the only bridge: it opens the SQLite ledger **read-only** (``mode=ro`` URI, no
schema change, no write, no network) and exports, for the case/recipient pairs E5 needs,
the six fields the identity check of 8.12 requires:

    stable_id | prompt_sha256 | returned_model | system_fingerprint | status | outcome

It never exports a prompt, a neutral text or a reasoning summary: identifiers, hashes,
model identity and the parsed label only. Run it after the batch is closed.

**This script settles two of the six identities, not six.** From the ledger alone it can
check identity 4 (same ``returned_model`` and ``system_fingerprint``) and the presence of
every requested slot, and it surfaces the recorded ``prompt_sha256`` and ``contract_sha256``
without being able to say what they should equal. Identity 3 (prompt byte-identical to the
one regenerated by the E5 path), identity 5 (the decoding contract of the E5 target) and
identity 6 (the same scoring function) are verified outside it, by comparison, and identity 4
is only complete once the E5 canary of the execution day matches. Its verdict is therefore
named ``partial_verdict`` and must never be reported as "the six identities hold": the
checklist that does that is ``VERIFICA_FULL_BLF.md``.

Usage
-----
    python3 studio2/fase03/e5/export_full_blf.py \\
        --ledger /Users/luker/fot-tep-runtime/<target>/ledger.sqlite3 \\
        --recipients studio2/fase03/e5/RICEVENTI_E5.json \\
        --out studio2/fase03/e5/FULL_BLF_EXPORT.json
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path

CONDITION = "B-LF"
DEFAULT_REPETITIONS = (1,)
LIBRARY_ROLE = "G_P"
BLOCK = "nucleus"


def open_read_only(path: Path) -> sqlite3.Connection:
    if not path.is_file():
        raise SystemExit(f"ledger not found: {path}")
    connection = sqlite3.connect(f"file:{path}?mode=ro&immutable=0", uri=True)
    connection.row_factory = sqlite3.Row
    return connection


def wanted_stable_ids(recipients: dict) -> dict[str, dict]:
    """The stable ids of the FULL slots, rebuilt from identifiers only.

    Stable id format of ``harness/final_inventory.stable_id``:
    ``block|condition|case_id|recipient_agent|library_role``.
    """
    wanted: dict[str, dict] = {}
    for case_id, agents in recipients["recipients"]["assignments"].items():
        for agent in agents:
            identifier = "|".join((BLOCK, CONDITION, case_id, agent, LIBRARY_ROLE))
            wanted[identifier] = {"case_id": case_id, "recipient_agent": agent}
    return wanted


def export(ledger: Path, wanted: dict[str, dict],
           repetitions: tuple[int, ...] = DEFAULT_REPETITIONS) -> dict:
    connection = open_read_only(ledger)
    rows = connection.execute(
        "SELECT r.request_id, r.logical_id, r.stage, r.status, r.identity_json, "
        "       r.prompt_tokens, r.completion_tokens, s.record_json "
        "FROM requests AS r LEFT JOIN responses AS s ON s.request_id = r.request_id"
    ).fetchall()
    found: dict[str, dict] = {}
    for row in rows:
        try:
            identity = json.loads(row["identity_json"])
        except (TypeError, json.JSONDecodeError):
            continue
        if identity.get("condition") != CONDITION:
            continue
        repetition = int(identity.get("repetition", -1))
        if repetition not in repetitions:
            continue
        stable = identity.get("group")
        if stable not in wanted:
            continue
        key = (stable, repetition)
        record = {}
        if row["record_json"]:
            try:
                record = json.loads(row["record_json"])
            except json.JSONDecodeError:
                record = {}
        parsed = record.get("parsed_output") or {}
        entry = {
            **wanted[stable],
            "stable_id": stable,
            "repetition": repetition,
            "logical_id": row["logical_id"],
            "request_id": row["request_id"],
            "stage": row["stage"],
            "status": row["status"],
            "prompt_sha256": identity.get("prompt_sha256"),
            "contract_sha256": identity.get("contract_sha256"),
            "returned_model": record.get("returned_model"),
            "returned_model_revision": record.get("returned_model_revision"),
            "system_fingerprint": record.get("system_fingerprint"),
            "finish_reason": record.get("finish_reason"),
            "truncated": record.get("truncated"),
            "schema_valid": record.get("schema_valid"),
            "predicted_label": parsed.get("predicted_label"),
            "abstain": parsed.get("abstain"),
            "prompt_tokens": row["prompt_tokens"],
        }
        previous = found.get(key)
        # keep the terminal attempt: a leaf with a record wins over an open INTENT
        if previous is None or (previous.get("returned_model") is None
                                and entry.get("returned_model") is not None):
            found[key] = entry
    connection.close()

    expected = {(stable, repetition) for stable in wanted for repetition in repetitions}
    missing = sorted(f"{stable}#r{repetition}" for stable, repetition in expected - set(found))
    fingerprints = sorted({row["system_fingerprint"] for row in found.values()
                           if row["system_fingerprint"]})
    models = sorted({row["returned_model"] for row in found.values() if row["returned_model"]})
    return {
        "artifact_version": "FULL_BLF_EXPORT_1",
        "scope": "read-only export of the B-LF repetition-1 slots reused as FULL",
        "ledger": str(ledger),
        "repetitions_requested": list(repetitions),
        "requested_slots": len(wanted) * len(repetitions),
        "exported_slots": len(found),
        "missing_slots": missing,
        "distinct_returned_models": models,
        "distinct_system_fingerprints": fingerprints,
        "partial_verdict": {
            "covers": ["identity 4 in part: one returned_model and one system_fingerprint "
                       "across the exported slots",
                       "presence of every requested slot"],
            "does_not_cover": [
                "identity 1 (case): compare case_id and neutral_text_sha256 with the test-lot "
                "evidence manifest",
                "identity 3 (prompt): compare prompt_sha256 with the FULL prompt regenerated "
                "by the E5 path",
                "identity 5 (decoding): compare contract_sha256 with the generation contract "
                "of the E5 target",
                "identity 6 (aggregation): the scoring function is reused, not checked here",
                "identity 4 completed: the E5 canary of the execution day must return the "
                "same fingerprint",
            ],
            "single_model": len(models) == 1,
            "single_fingerprint": len(fingerprints) == 1,
            "no_missing_slot": not missing,
            "verdict": ("PARTIAL_OK" if len(models) == 1 and len(fingerprints) == 1
                        and not missing else "STOP"),
            "rule": ("STOP on more than one model or fingerprint, or on a missing slot. "
                     "PARTIAL_OK is not a GO for the reuse of FULL: the remaining identities "
                     "are checked in VERIFICA_FULL_BLF.md, and only that checklist decides. "
                     "A STOP means FULL is re-run, with an explicit decision."),
        },
        "slots": [found[key] for key in sorted(found)],
        "reminder": ("predicted_label is exported for the analysis phase. Do not look at it "
                     "before the E5 protocol is frozen."),
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=Path, required=True)
    parser.add_argument("--recipients", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--repetitions", type=int, nargs="+", default=list(DEFAULT_REPETITIONS),
                        help="repetitions to export: 1 for the primary reuse, 1 2 3 when "
                             "decision B puts the three B-LF repetitions in the reuse contract")
    arguments = parser.parse_args(argv)
    recipients = json.loads(arguments.recipients.read_text(encoding="utf-8"))
    payload = export(arguments.ledger, wanted_stable_ids(recipients),
                     tuple(arguments.repetitions))
    arguments.out.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
                             encoding="utf-8")
    print(json.dumps({key: value for key, value in payload.items() if key != "slots"},
                     indent=2, ensure_ascii=False))
    return 0 if payload["partial_verdict"]["verdict"] == "PARTIAL_OK" else 1


if __name__ == "__main__":
    raise SystemExit(main())
