function [cleanupGuard, state] = configure_exp3v2_model(modelName)
%CONFIGURE_EXP3V2_MODEL Temporarily configure non-scientific output handling.

assert(bdIsLoaded(modelName), 'EXP3V2:ModelNotLoaded', ...
    'Model must be loaded before temporary configuration.');
originalStopFcn = get_param(modelName, 'StopFcn');
originalReturnWorkspaceOutputs = ...
    get_param(modelName, 'ReturnWorkspaceOutputs');
originalDirty = get_param(modelName, 'Dirty');
assert(strcmp(originalStopFcn, 'TEplot'), ...
    'EXP3V2:StopCallbackMismatch', ...
    'Expected the exact frozen StopFcn TEplot.');
assert(strcmp(originalReturnWorkspaceOutputs, 'off'), ...
    'EXP3V2:ReturnWorkspaceOutputsMismatch', ...
    'Expected the exact frozen ReturnWorkspaceOutputs value off.');

state = struct( ...
    'model_name', modelName, ...
    'original_stopfcn', originalStopFcn, ...
    'original_return_workspace_outputs', originalReturnWorkspaceOutputs, ...
    'original_dirty', originalDirty);
cleanupGuard = onCleanup(@() restore_exp3v2_model_config(state));
set_param(modelName, 'StopFcn', '');
set_param(modelName, 'ReturnWorkspaceOutputs', 'on');
assert(strcmp(get_param(modelName, 'StopFcn'), ''), ...
    'EXP3V2:StopCallbackSuppressFailed', ...
    'StopFcn suppression failed.');
assert(strcmp(get_param(modelName, 'ReturnWorkspaceOutputs'), 'on'), ...
    'EXP3V2:ReturnWorkspaceOutputsEnableFailed', ...
    'ReturnWorkspaceOutputs was not enabled.');
end
