function [cleanupGuard, state] = configure_exp3v2_file_generation( ...
        throwawayRoot, repoRoot, sourceSimulatorDir)
%CONFIGURE_EXP3V2_FILE_GENERATION Isolate generated files in throwaway root.

throwawayRoot = canonical_path(throwawayRoot);
repoRoot = canonical_path(repoRoot);
sourceSimulatorDir = canonical_path(sourceSimulatorDir);
assert(isfolder(throwawayRoot), 'EXP3V2:FileGenThrowawayMissing', ...
    'Validated throwaway root must exist before file-generation setup.');
assert(~paths_overlap(throwawayRoot, repoRoot) && ...
    ~paths_overlap(throwawayRoot, sourceSimulatorDir), ...
    'EXP3V2:FileGenUnsafeRoot', ...
    'File-generation root must be disjoint from source and Git worktree.');

cacheFolder = fullfile(throwawayRoot, 'simulink-cache');
codeGenFolder = fullfile(throwawayRoot, 'simulink-codegen');
originalConfig = Simulink.fileGenControl('getConfig');
state = struct( ...
    'original_config', originalConfig, ...
    'original_path', path, ...
    'cache_folder', cacheFolder, ...
    'codegen_folder', codeGenFolder);
cleanupGuard = onCleanup(@() restore_exp3v2_file_generation(state));
Simulink.fileGenControl('set', ...
    'CacheFolder', cacheFolder, ...
    'CodeGenFolder', codeGenFolder, ...
    'keepPreviousPath', false, ...
    'createDir', true);
observed = Simulink.fileGenControl('getConfig');
assert(strcmp(canonical_path(observed.CacheFolder), ...
    canonical_path(cacheFolder)) && ...
    strcmp(canonical_path(observed.CodeGenFolder), ...
    canonical_path(codeGenFolder)), ...
    'EXP3V2:FileGenConfigurationFailed', ...
    'Simulink file-generation folders were not isolated.');
assert(is_within(canonical_path(cacheFolder), throwawayRoot) && ...
    is_within(canonical_path(codeGenFolder), throwawayRoot), ...
    'EXP3V2:FileGenEscapedThrowaway', ...
    'Generated-file directories escaped the throwaway root.');
end

function value = canonical_path(pathValue)
value = char(java.io.File(char(string(pathValue))).getCanonicalPath());
end

function result = paths_overlap(left, right)
result = is_within(left, right) || is_within(right, left);
end

function result = is_within(candidate, root)
result = strcmp(candidate, root) || startsWith(candidate, [root filesep]);
end
