function [present, expression] = exp3v2_workspace_outputs_present()
%EXP3V2_WORKSPACE_OUTPUTS_PRESENT Detect stale base outputs with scalar text.

expression = "exist('tout','var') || " + ...
    "exist('simout','var') || exist('xmv','var')";
assert((ischar(expression) && isrow(expression)) || ...
    (isstring(expression) && isscalar(expression)), ...
    'EXP3V2:WorkspaceIsolationExpression', ...
    'The base-workspace isolation expression must be a text scalar.');
present = logical(evalin('base', expression));
end
