function numericOutput = extract_exp3v2_outputs(simResult, expectedRows)
%EXTRACT_EXP3V2_OUTPUTS Accept only current SimulationOutput-owned variables.

assert(isa(simResult, 'Simulink.SimulationOutput'), ...
    'EXP3V2:SimulationOutputType', ...
    'sim must return a Simulink.SimulationOutput.');
availableOutputs = string(who(simResult));
requiredOutputs = ["tout" "simout" "xmv"];
assert(all(ismember(requiredOutputs, availableOutputs)), ...
    'EXP3V2:SimulationOutputsMissing', ...
    'SimulationOutput must contain tout, simout, and xmv.');

tout = simResult.get('tout');
simout = simResult.get('simout');
xmv = simResult.get('xmv');
assert(isnumeric(tout) && isnumeric(simout) && isnumeric(xmv), ...
    'EXP3V2:SimulationOutputsType', ...
    'SimulationOutput variables must be numeric.');
assert(isequal(size(tout), [expectedRows 1]) && ...
    isequal(size(simout), [expectedRows 41]) && ...
    isequal(size(xmv), [expectedRows 12]), ...
    'EXP3V2:SimulationOutputsShape', ...
    'Expected current-invocation output shapes 3001x1, 3001x41, 3001x12.');
numericOutput = [double(tout), double(simout), double(xmv)];
end
