function value = format_exp3v2_csv_scalar(input)
%FORMAT_EXP3V2_CSV_SCALAR Deterministically serialize one safe CSV scalar.

if islogical(input)
    assert(isscalar(input), 'EXP3V2:CsvLogicalScalar', ...
        'Logical CSV values must be scalar.');
    value = lower(char(string(input)));
elseif isnumeric(input)
    assert(isscalar(input) && isreal(input) && isfinite(input), ...
        'EXP3V2:CsvNumericScalar', ...
        'Numeric CSV values must be finite real scalars.');
    value = sprintf('%.17g', double(input));
else
    assert((ischar(input) && isrow(input)) || ...
        (isstring(input) && isscalar(input)), ...
        'EXP3V2:CsvTextScalar', ...
        'Text CSV values must be character vectors or string scalars.');
    value = char(input);
    assert(~any(contains(value, {',', '"', newline, char(13)})), ...
        'EXP3V2:CsvUnsafeText', ...
        'Text CSV values must not require CSV escaping.');
end
end
