function record = generate_exp3v2_sentinel(throwawayDir, varargin)
%GENERATE_EXP3V2_SENTINEL Authorize only the frozen sentinel identity.

parser = inputParser;
parser.addRequired('throwawayDir', @(x) ischar(x) || isstring(x));
parser.addParameter('SimulatorDir', '', @(x) ischar(x) || isstring(x));
parser.parse(throwawayDir, varargin{:});

scriptDir = fileparts([mfilename('fullpath') '.m']);
repoRoot = fileparts(fileparts(scriptDir));
planPath = fullfile(scriptDir, 'exp3v2_case_plan.json');
descriptorPath = fullfile(scriptDir, 'exp3v2_sentinel_case.json');
harnessManifestPath = fullfile(scriptDir, ...
    'EXP3_V2_HARNESS_FREEZE_MANIFEST.json');
simulatorDir = default_path(parser.Results.SimulatorDir, ...
    fullfile(repoRoot, 'tep_parent_a0413e16', 'simulator'));

plan = jsondecode(fileread(planPath));
descriptor = jsondecode(fileread(descriptorPath));
harnessManifest = assert_exp3v2_freeze_boundary(harnessManifestPath, ...
    'HARNESS_FROZEN_FOR_SENTINEL', 'exp3-v2-harness-frozen', repoRoot);
assert(harnessManifest.sentinel_runs_at_freeze == 0, ...
    'EXP3V2:SentinelAlreadyPresentAtFreeze', ...
    'Harness freeze must precede every V2 sentinel execution.');
assert(strcmp(descriptor.status, 'SENTINEL_VALIDATION_ONLY') && ...
    strcmp(descriptor.physical_case_id, 'EXP3V2-SENTINEL-001') && ...
    descriptor.seed == 987654321 && ...
    strcmp(descriptor.rng_algorithm, 'twister') && ...
    ~descriptor.replacement_allowed, ...
    'EXP3V2:SentinelDescriptor', 'Sentinel descriptor mismatch.');

realIds = string({plan.cases.physical_case_id});
primarySeeds = double([plan.cases.primary_seed]);
replacementSeeds = double([plan.cases.replacement_seed]);
assert(~ismember(string(descriptor.physical_case_id), realIds) && ...
    ~ismember(double(descriptor.seed), primarySeeds) && ...
    ~ismember(double(descriptor.seed), replacementSeeds) && ...
    descriptor.seed ~= plan.rng.bootstrap_seed, ...
    'EXP3V2:SentinelCollision', ...
    'Sentinel identity and seed must be disjoint from every real allocation.');

throwawayDir = canonical_path(char(string(throwawayDir)));
assert(isfolder(throwawayDir), 'EXP3V2:ThrowawayMissing', ...
    'The validated throwaway directory must already exist.');
realV2Root = canonical_path(fullfile(repoRoot, 'tep_exp3_v2_heldout'));
realExp3Root = canonical_path(fullfile(repoRoot, 'tep_exp3_heldout'));
assert(~paths_overlap(throwawayDir, realV2Root) && ...
    ~paths_overlap(throwawayDir, realExp3Root), ...
    'EXP3V2:SentinelRealPathOverlap', ...
    'Throwaway path must not equal, contain, or be inside a real output root.');

outputDir = fullfile(throwawayDir, 'mode1');
attemptLogPath = fullfile(throwawayDir, 'sentinel_attempt_log.json');
config = struct( ...
    'mode', 'sentinel', ...
    'identity', struct( ...
        'physical_case_id', descriptor.physical_case_id, ...
        'condition', descriptor.condition, ...
        'run_index', 1, ...
        'rng_algorithm', descriptor.rng_algorithm, ...
        'primary_seed', descriptor.seed, ...
        'replacement_seed', descriptor.seed, ...
        'max_total_attempts', 1), ...
    'attempt', 0, ...
    'case_plan', plan, ...
    'case_plan_path', descriptorPath, ...
    'boundary_manifest_path', harnessManifestPath, ...
    'output_dir', outputDir, ...
    'attempt_log_path', attemptLogPath, ...
    'simulator_dir', simulatorDir, ...
    'repo_root', repoRoot);
record = run_exp3v2_engine(config);
end

function value = default_path(provided, fallback)
if strlength(string(provided)) == 0
    value = fallback;
else
    value = char(string(provided));
end
end

function value = canonical_path(pathValue)
value = char(java.io.File(pathValue).getCanonicalPath());
end

function result = paths_overlap(left, right)
result = is_within(left, right) || is_within(right, left);
end

function result = is_within(candidate, root)
result = strcmp(candidate, root) || ...
    startsWith(candidate, [root filesep]);
end
