function record = generate_exp3v2_heldout(physicalCaseId, attempt, varargin)
%GENERATE_EXP3V2_HELDOUT Authorize one final-frozen real V2 attempt.
%
% This wrapper accepts only the 30 pre-specified real IDs and exact real
% destinations. It cannot authorize the sentinel.

parser = inputParser;
parser.addRequired('physicalCaseId', @(x) ischar(x) || isstring(x));
parser.addRequired('attempt', ...
    @(x) isnumeric(x) && isscalar(x) && ismember(x, [0 1]));
parser.addParameter('SimulatorDir', '', @(x) ischar(x) || isstring(x));
parser.parse(physicalCaseId, attempt, varargin{:});

physicalCaseId = char(string(parser.Results.physicalCaseId));
attempt = double(parser.Results.attempt);
scriptDir = fileparts([mfilename('fullpath') '.m']);
repoRoot = fileparts(fileparts(scriptDir));
casePlanPath = fullfile(scriptDir, 'exp3v2_case_plan.json');
freezeManifestPath = fullfile(scriptDir, 'EXP3_V2_FREEZE_MANIFEST.json');
outputDir = fullfile(repoRoot, 'tep_exp3_v2_heldout', 'mode1');
attemptLogPath = fullfile(repoRoot, ...
    'tep_exp3_v2_heldout', 'exp3v2_attempt_log.json');
simulatorDir = char(string(parser.Results.SimulatorDir));
assert(strlength(string(simulatorDir)) > 0, ...
    'EXP3V2:ExplicitRuntimeRequired', ...
    'Real generation requires an explicitly materialized runtime directory.');

plan = jsondecode(fileread(casePlanPath));
assert(strcmp(plan.status, 'FROZEN_BEFORE_GENERATION'), ...
    'EXP3V2:PlanNotFrozen', ...
    'Real generation requires case-plan status FROZEN_BEFORE_GENERATION.');
freezeManifest = assert_exp3v2_freeze_boundary(freezeManifestPath, ...
    'FROZEN_BEFORE_GENERATION', 'exp3-v2-heldout-frozen', repoRoot);
assert(freezeManifest.v2_workbooks_at_freeze == 0 && ...
    freezeManifest.sentinel_validation_passed, ...
    'EXP3V2:FinalFreezeEvidence', ...
    'Final freeze must bind sentinel PASS and zero real workbooks.');

ids = string({plan.cases.physical_case_id});
index = find(ids == string(physicalCaseId));
assert(isscalar(index), 'EXP3V2:RealCaseLookup', ...
    'The ID must match exactly one of the 30 real cases.');
assert(~strcmp(physicalCaseId, 'EXP3V2-SENTINEL-001'), ...
    'EXP3V2:SentinelRejectedByRealWrapper', ...
    'The real wrapper refuses the sentinel identity.');

config = struct( ...
    'mode', 'real', ...
    'identity', plan.cases(index), ...
    'attempt', attempt, ...
    'case_plan', plan, ...
    'case_plan_path', casePlanPath, ...
    'boundary_manifest_path', freezeManifestPath, ...
    'output_dir', outputDir, ...
    'attempt_log_path', attemptLogPath, ...
    'simulator_dir', simulatorDir, ...
    'repo_root', repoRoot);
record = run_exp3v2_engine(config);
end
