function restore_exp3v2_file_generation(state)
%RESTORE_EXP3V2_FILE_GENERATION Restore session file-generation configuration.

assert(isstruct(state) && isfield(state, 'original_config') && ...
    isfield(state, 'original_path'), 'EXP3V2:FileGenRestoreState', ...
    'File-generation restoration state is incomplete.');
Simulink.fileGenControl('setConfig', ...
    'config', state.original_config, ...
    'keepPreviousPath', false, ...
    'createDir', true);
path(state.original_path);
observed = Simulink.fileGenControl('getConfig');
assert(strcmp(char(string(observed.CacheFolder)), ...
    char(string(state.original_config.CacheFolder))) && ...
    strcmp(char(string(observed.CodeGenFolder)), ...
    char(string(state.original_config.CodeGenFolder))) && ...
    isequal(observed.CodeGenFolderStructure, ...
    state.original_config.CodeGenFolderStructure), ...
    'EXP3V2:FileGenRestoreFailed', ...
    'Simulink file-generation configuration was not restored exactly.');
assert(strcmp(path, state.original_path), 'EXP3V2:FileGenPathRestoreFailed', ...
    'MATLAB path was not restored after file-generation isolation.');
end
