function restore_exp3v2_model_config(state)
%RESTORE_EXP3V2_MODEL_CONFIG Restore all temporary in-memory model changes.

if ~isstruct(state) || ~all(isfield(state, { ...
        'model_name', 'original_stopfcn', ...
        'original_return_workspace_outputs', 'original_dirty'}))
    error('EXP3V2:InvalidModelConfigState', ...
        'Model configuration restoration state is invalid.');
end
modelName = state.model_name;
if ~bdIsLoaded(modelName)
    return;
end
set_param(modelName, 'ReturnWorkspaceOutputs', ...
    state.original_return_workspace_outputs);
set_param(modelName, 'StopFcn', state.original_stopfcn);
set_param(modelName, 'Dirty', state.original_dirty);
assert(strcmp(get_param(modelName, 'StopFcn'), state.original_stopfcn), ...
    'EXP3V2:StopCallbackRestoreFailed', 'StopFcn restoration failed.');
assert(strcmp(get_param(modelName, 'ReturnWorkspaceOutputs'), ...
    state.original_return_workspace_outputs), ...
    'EXP3V2:ReturnWorkspaceOutputsRestoreFailed', ...
    'ReturnWorkspaceOutputs restoration failed.');
assert(strcmp(get_param(modelName, 'Dirty'), state.original_dirty), ...
    'EXP3V2:ModelDirtyRestoreFailed', ...
    'The original model Dirty state was not restored.');
end
