function record = run_exp3v2_engine(config)
%RUN_EXP3V2_ENGINE Shared real/sentinel generation and structural-check engine.
%
% Authorization and destinations differ between wrappers. Configuration,
% simulator checks, temporary model changes, RNG placement, typed output
% retrieval, workbook writing, and structural validation are identical.

requiredConfig = {'mode', 'identity', 'attempt', 'case_plan', ...
    'case_plan_path', 'boundary_manifest_path', 'output_dir', ...
    'attempt_log_path', 'simulator_dir', 'repo_root'};
assert(all(isfield(config, requiredConfig)), 'EXP3V2:EngineConfig', ...
    'Shared-engine configuration is incomplete.');
assert(ismember(config.mode, {'real', 'sentinel'}), ...
    'EXP3V2:EngineMode', 'Engine mode must be real or sentinel.');
assert_plan_constants(config.case_plan);
assert_mode_paths(config);

entry = config.identity;
attempt = double(config.attempt);
if strcmp(config.mode, 'sentinel')
    assert(strcmp(entry.physical_case_id, 'EXP3V2-SENTINEL-001') && ...
        attempt == 0 && entry.primary_seed == 987654321, ...
        'EXP3V2:SentinelAuthorization', ...
        'Sentinel mode accepts only the fixed identity, seed, and attempt 0.');
    seed = double(entry.primary_seed);
else
    assert(ismember(attempt, [0 1]), 'EXP3V2:AttemptValue', ...
        'Real attempt must be 0 or 1.');
    if attempt == 0
        seed = double(entry.primary_seed);
    else
        seed = double(entry.replacement_seed);
    end
end

attemptLog = read_attempt_log(config.attempt_log_path);
assert_attempt_allowed(attemptLog, entry, attempt, seed, config.mode);
if ~isfolder(config.output_dir)
    mkdir(config.output_dir);
end
outputFilename = sprintf('%s__attempt-%d.xlsx', ...
    entry.physical_case_id, attempt);
outputPath = fullfile(config.output_dir, outputFilename);
assert(~isfile(outputPath), 'EXP3V2:RefuseOverwrite', ...
    'Refusing to overwrite existing output: %s', outputPath);

expected = config.case_plan.simulator;
runtimeManifest = jsondecode(fileread(config.boundary_manifest_path));
assert_exp3v2_runtime_bundle(config.simulator_dir, runtimeManifest);
modelName = char(expected.model);
modelPath = fullfile(config.simulator_dir, [modelName '.mdl']);
initialStatePath = fullfile(config.simulator_dir, ...
    char(expected.initial_state_file));
sfunctionSourcePath = fullfile(config.simulator_dir, 'temexd_mod.c');
sfunctionMexPath = fullfile(config.simulator_dir, 'temexd_mod.mexmaca64');
assert(strcmp(sha256_file(modelPath), char(expected.model_sha256)), ...
    'EXP3V2:ModelHashMismatch', 'Simulator model hash mismatch.');
assert(strcmp(sha256_file(initialStatePath), ...
    char(expected.initial_state_sha256)), ...
    'EXP3V2:InitialStateHashMismatch', 'Initial-state hash mismatch.');
assert(strcmp(sha256_file(sfunctionSourcePath), ...
    char(expected.sfunction_source_sha256)), ...
    'EXP3V2:SFunctionSourceHashMismatch', 'S-function source hash mismatch.');
assert(strcmp(sha256_file(sfunctionMexPath), ...
    char(expected.sfunction_macos_mex_sha256)), ...
    'EXP3V2:SFunctionMexHashMismatch', 'S-function MEX hash mismatch.');

enginePath = [mfilename('fullpath') '.m'];
generationScriptHash = sha256_file(enginePath);
casePlanHash = sha256_file(config.case_plan_path);
runtime = capture_runtime();
assert_runtime(runtime, config.case_plan.runtime);
startedAt = utc_timestamp();
record = empty_record(entry.physical_case_id, entry.condition, attempt, seed, ...
    runtime, expected, casePlanHash, generationScriptHash, outputPath, startedAt);

originalPath = path;
originalDir = pwd;
environmentGuard = onCleanup(@() cleanup_environment( ...
    originalPath, originalDir, modelName));
configState = struct([]);
configGuard = [];
simulationStarted = false;

try
    addpath(config.simulator_dir, '-begin');
    addpath(fileparts(enginePath), '-begin');
    cd(config.simulator_dir);
    rehash;
    close_if_loaded(modelName);
    close_if_loaded('TElib');
    close_if_loaded('tesys');
    load_system(modelName);
    assert_model_configuration(modelName, modelPath, expected);

    teBlocks = find_system(modelName, 'LookUnderMasks', 'all', ...
        'FollowLinks', 'on', 'Name', 'TE Code');
    assert(isscalar(teBlocks), 'EXP3V2:SFunctionBlockCount', ...
        'Expected exactly one TE Code block.');
    assert(strcmp(get_param(teBlocks{1}, 'FunctionName'), ...
        char(expected.sfunction_identity)), ...
        'EXP3V2:SFunctionIdentityMismatch', ...
        'S-function identity mismatch.');
    assert(strcmp(strtrim(get_param(teBlocks{1}, 'Parameters')), '[] rand()'), ...
        'EXP3V2:SFunctionParametersMismatch', ...
        'S-function parameters must remain exactly [] rand().');

    [configGuard, configState] = configure_exp3v2_model(modelName);
    dist = zeros(1, 28);
    if ~strcmp(char(entry.condition), 'Normal')
        faultIndex = sscanf(char(entry.condition), 'F%d');
        assert(ismember(faultIndex, [1 8 10 13]), ...
            'EXP3V2:UnexpectedFault', 'Unexpected fault condition.');
        dist(faultIndex) = 1;
    end
    assignin('base', 'dist', dist);

    % Stale base-workspace variables can never be accepted as run output.
    evalin('base', 'clear tout simout xmv');
    assert(~exp3v2_workspace_outputs_present(), ...
        'EXP3V2:WorkspaceIsolationFailed', ...
        'Potentially conflicting base-workspace outputs were not cleared.');
    clear simResult numericOutput;

    % PROTOCOL-CRITICAL: rng is the last random-relevant statement before sim.
    rng(seed, 'twister');
    simResult = sim(modelName);
    simulationStarted = true;

    % The local object above came directly from this invocation. No base-
    % workspace fallback exists or is permitted.
    numericOutput = extract_exp3v2_outputs(simResult, expected.expected_rows);
    restore_exp3v2_model_config(configState);
    clear configGuard configState;
    assert_model_restored(modelName);
    assert(strcmp(sha256_file(modelPath), char(expected.model_sha256)), ...
        'EXP3V2:ModelChangedAfterSimulation', ...
        'The pinned model file changed during execution.');

    observed = inspect_numeric_output(numericOutput, expected);
    if ~observed.structural_valid
        error('EXP3V2:StructuralInvalid', '%s', observed.failure_reason);
    end
    headers = [{'Time (h)'}, ...
        arrayfun(@(i) sprintf('XMEAS-%d', i), 1:41, ...
        'UniformOutput', false), ...
        arrayfun(@(i) sprintf('XMV-%d', i), 1:12, ...
        'UniformOutput', false)];
    writecell(headers, outputPath, 'Sheet', char(expected.worksheet), ...
        'Range', 'A1');
    writematrix(numericOutput, outputPath, ...
        'Sheet', char(expected.worksheet), 'Range', 'A2');
    verify_written_workbook(outputPath, headers, numericOutput, expected);
    fileInfo = dir(outputPath);

    record.completed_at = utc_timestamp();
    record.output_size_bytes = fileInfo.bytes;
    record.output_sha256 = sha256_file(outputPath);
    record.rows = observed.rows;
    record.cols = observed.cols;
    record.time_start = observed.time_start;
    record.time_end = observed.time_end;
    record.sampling_interval = observed.sampling_interval;
    record.finite_check = observed.finite_check;
    record.structural_valid = true;
    append_exp3v2_attempt_record(config.attempt_log_path, attemptLog, record);
catch exception
    if ~isempty(configGuard) && isstruct(configState)
        try
            restore_exp3v2_model_config(configState);
            clear configGuard configState;
            assert_model_restored(modelName);
            assert(strcmp(sha256_file(modelPath), char(expected.model_sha256)), ...
                'EXP3V2:ModelChangedAfterException', ...
                'The pinned model file changed after an exception.');
        catch restoreException
            combined = MException('EXP3V2:ModelConfigRestoreFailed', ...
                'Model configuration restoration failed after an exception.');
            combined = addCause(combined, exception);
            combined = addCause(combined, restoreException);
            exception = combined;
        end
    end
    record.completed_at = utc_timestamp();
    record.technical_failure_reason = sprintf('%s: %s', ...
        exception.identifier, exception.message);
    if simulationStarted && isfile(outputPath)
        fileInfo = dir(outputPath);
        record.output_size_bytes = fileInfo.bytes;
        record.output_sha256 = sha256_file(outputPath);
    end
    append_exp3v2_attempt_record(config.attempt_log_path, attemptLog, record);
    rethrow(exception);
end
end

function assert_plan_constants(plan)
assert(ismember(plan.status, {'PRE_FREEZE_DRAFT', ...
    'FROZEN_BEFORE_GENERATION'}), 'EXP3V2:PlanStatus', ...
    'Unexpected case-plan status.');
assert(strcmp(plan.rng.algorithm, 'twister') && ...
    plan.rng.master_allocation_base == 320000 && ...
    plan.rng.bootstrap_seed == 320031 && ...
    isequal(double(plan.rng.allowed_attempts(:))', [0 1]) && ...
    plan.rng.max_total_attempts == 2, 'EXP3V2:RngPlan', ...
    'RNG plan mismatch.');
assert(numel(plan.cases) == 30, 'EXP3V2:CaseCount', ...
    'Case plan must contain 30 cases.');
conditions = {'Normal', 'F1', 'F8', 'F10', 'F13'};
ordinal = 0;
for conditionIndex = 1:numel(conditions)
    for runIndex = 1:6
        ordinal = ordinal + 1;
        entry = plan.cases(ordinal);
        prefix = conditions{conditionIndex};
        if strcmp(prefix, 'Normal')
            prefix = 'N';
        end
        assert(strcmp(entry.physical_case_id, ...
            sprintf('EXP3V2-%s-%03d', prefix, runIndex)) && ...
            strcmp(entry.condition, conditions{conditionIndex}) && ...
            entry.run_index == runIndex && ...
            entry.primary_seed == 320000 + ordinal && ...
            entry.replacement_seed == 1320000 + ordinal && ...
            entry.max_total_attempts == 2, ...
            'EXP3V2:CanonicalPlan', 'Case plan is not canonical.');
    end
end
expected = plan.simulator;
assert(strcmp(expected.simulator_commit, ...
    'a0413e16c940f0fc8b554d6a86248020d7fb7527') && ...
    strcmp(expected.model, 'MultiLoop_mode1') && ...
    strcmp(expected.tep_mode, 'Mode 1') && ...
    strcmp(expected.simulation_mode, 'normal') && ...
    strcmp(expected.solver, 'ode45') && ...
    expected.start_time_h == 0 && expected.stop_time_h == 50 && ...
    abs(expected.sampling_interval_h - 1/60) <= 1e-15 && ...
    expected.fault_injection_h == 10 && ~expected.custom_setpoints && ...
    expected.expected_rows == 3001 && expected.expected_columns == 54 && ...
    strcmp(expected.worksheet, 'Sheet1'), ...
    'EXP3V2:ScientificInvariant', ...
    'A frozen scientific invariant differs from EXP3.');
end

function assert_mode_paths(config)
repoRoot = canonical_path(config.repo_root);
outputDir = canonical_path(config.output_dir);
attemptLogPath = canonical_path(config.attempt_log_path);
realRoot = canonical_path(fullfile(repoRoot, 'tep_exp3_v2_heldout'));
oldRoot = canonical_path(fullfile(repoRoot, 'tep_exp3_heldout'));
if strcmp(config.mode, 'real')
    assert(is_within(outputDir, realRoot) && ...
        is_within(attemptLogPath, realRoot), 'EXP3V2:RealPathBoundary', ...
        'Real execution may write only beneath tep_exp3_v2_heldout.');
else
    assert(~paths_overlap(outputDir, realRoot) && ...
        ~paths_overlap(outputDir, oldRoot) && ...
        ~paths_overlap(attemptLogPath, realRoot) && ...
        ~paths_overlap(attemptLogPath, oldRoot), ...
        'EXP3V2:SentinelPathBoundary', ...
        'Sentinel paths must be disjoint from both real output roots.');
end
end

function log = read_attempt_log(path)
if isfile(path)
    log = jsondecode(fileread(path));
else
    log = struct( ...
        'schema_version', '1.0', ...
        'experiment', 'Experiment 3 V2 — Prospective Fresh-Run Held-Out', ...
        'attempts', []);
end
assert(strcmp(log.schema_version, '1.0') && ...
    strcmp(log.experiment, ...
    'Experiment 3 V2 — Prospective Fresh-Run Held-Out'), ...
    'EXP3V2:AttemptLogIdentity', 'Attempt-log identity mismatch.');
end

function assert_attempt_allowed(log, entry, attempt, seed, mode)
attempts = log.attempts;
if isempty(attempts)
    prior = struct('attempt', {}, 'structural_valid', {}, ...
        'technical_failure_reason', {});
else
    prior = attempts(strcmp({attempts.physical_case_id}, ...
        entry.physical_case_id));
end
assert(~any([prior.attempt] == attempt), 'EXP3V2:DuplicateAttempt', ...
    'This case/attempt already exists in the append-only log.');
if strcmp(mode, 'sentinel')
    assert(attempt == 0 && isempty(prior), 'EXP3V2:SentinelAttemptPolicy', ...
        'The sentinel permits one attempt and no replacement.');
    return;
end
if attempt == 0
    assert(seed == entry.primary_seed, 'EXP3V2:PrimarySeedMismatch', ...
        'Attempt 0 must use the primary seed.');
else
    assert(seed == entry.replacement_seed, ...
        'EXP3V2:ReplacementSeedMismatch', ...
        'Attempt 1 must use the replacement seed.');
    primary = prior([prior.attempt] == 0);
    assert(isscalar(primary), 'EXP3V2:ReplacementWithoutPrimary', ...
        'Attempt 1 requires exactly one logged attempt 0.');
    assert(~primary.structural_valid && ...
        strlength(string(primary.technical_failure_reason)) > 0, ...
        'EXP3V2:UnauthorizedReplacement', ...
        'Attempt 1 requires a technical failure on attempt 0.');
end
assert(numel(prior) < 2, 'EXP3V2:AttemptLimit', ...
    'Maximum two total attempts per real case.');
end

function assert_model_configuration(modelName, modelPath, expected)
assert(strcmp(get_param(modelName, 'FileName'), modelPath), ...
    'EXP3V2:WrongModelPath', 'Loaded model path mismatch.');
assert(strcmp(get_param(modelName, 'SimulationMode'), ...
    char(expected.simulation_mode)), 'EXP3V2:SimulationModeMismatch', ...
    'Simulation mode mismatch.');
assert(strcmp(get_param(modelName, 'Solver'), char(expected.solver)), ...
    'EXP3V2:SolverMismatch', 'Solver mismatch.');
assert(str2double(get_param(modelName, 'StartTime')) == ...
    expected.start_time_h && ...
    str2double(get_param(modelName, 'StopTime')) == expected.stop_time_h, ...
    'EXP3V2:TimeConfigurationMismatch', 'Simulation horizon mismatch.');
assert(strcmp(get_param(modelName, 'LoadInitialState'), 'on') && ...
    strcmp(get_param(modelName, 'InitialState'), 'xInitial') && ...
    strcmp(strtrim(get_param(modelName, 'PreLoadFcn')), 'Mode_1_Init') && ...
    strcmp(get_param(modelName, 'StopFcn'), 'TEplot') && ...
    strcmp(get_param(modelName, 'ReturnWorkspaceOutputs'), 'off'), ...
    'EXP3V2:ModelConfigurationMismatch', ...
    'Pinned callback, initial-state, or output configuration mismatch.');
assert(evalin('base', "exist('xInitial','var') == 1"), ...
    'EXP3V2:InitialStateMissing', ...
    'Mode1xInitial did not provide xInitial.');
end

function assert_model_restored(modelName)
assert(strcmp(get_param(modelName, 'StopFcn'), 'TEplot') && ...
    strcmp(get_param(modelName, 'ReturnWorkspaceOutputs'), 'off'), ...
    'EXP3V2:ModelConfigNotRestored', ...
    'StopFcn or ReturnWorkspaceOutputs was not restored.');
end

function runtime = capture_runtime()
matlabProduct = ver('MATLAB'); %#ok<VERMATLAB>
simulinkProduct = ver('Simulink');
exactVersion = version;
buildToken = regexp(exactVersion, '\.(\d+) \(R\d{4}[ab]\)', ...
    'tokens', 'once');
assert(~isempty(buildToken), 'EXP3V2:MatlabBuildUnavailable', ...
    'Could not parse MATLAB build from version string.');
runtime = struct( ...
    'matlab_version_full', exactVersion, ...
    'matlab_release', version('-release'), ...
    'matlab_build', buildToken{1}, ...
    'matlab_product_date', matlabProduct.Date, ...
    'matlab_runtime_update_date', version('-date'), ...
    'simulink_version', simulinkProduct.Version, ...
    'simulink_release', simulinkProduct.Release, ...
    'simulink_product_date', simulinkProduct.Date, ...
    'architecture', computer, ...
    'matlabroot', matlabroot);
end

function assert_runtime(actual, expected)
fields = {'matlab_version_full', 'matlab_release', 'matlab_build', ...
    'matlab_product_date', 'matlab_runtime_update_date', ...
    'simulink_version', 'simulink_release', 'simulink_product_date', ...
    'architecture', 'matlabroot'};
identifiers = {'MatlabVersionMismatch', 'MatlabReleaseMismatch', ...
    'MatlabBuildMismatch', 'MatlabProductDateMismatch', ...
    'MatlabRuntimeUpdateDateMismatch', 'SimulinkVersionMismatch', ...
    'SimulinkReleaseMismatch', 'SimulinkDateMismatch', ...
    'ArchitectureMismatch', 'MatlabRootMismatch'};
for index = 1:numel(fields)
    field = fields{index};
    assert(strcmp(actual.(field), expected.(field)), ...
        ['EXP3V2:' identifiers{index}], 'Runtime field mismatch: %s', field);
end
end

function record = empty_record(caseId, faultStatus, attempt, seed, runtime, ...
        expected, casePlanHash, scriptHash, outputPath, startedAt)
record = struct( ...
    'physical_case_id', caseId, ...
    'fault_status', faultStatus, ...
    'attempt', attempt, ...
    'seed', seed, ...
    'rng_algorithm', 'twister', ...
    'started_at', startedAt, ...
    'completed_at', '', ...
    'matlab_version_full', runtime.matlab_version_full, ...
    'matlab_release', runtime.matlab_release, ...
    'matlab_build', runtime.matlab_build, ...
    'matlab_product_date', runtime.matlab_product_date, ...
    'matlab_runtime_update_date', runtime.matlab_runtime_update_date, ...
    'simulink_version', runtime.simulink_version, ...
    'simulink_release', runtime.simulink_release, ...
    'simulink_product_date', runtime.simulink_product_date, ...
    'architecture', runtime.architecture, ...
    'matlabroot', runtime.matlabroot, ...
    'simulator_commit', expected.simulator_commit, ...
    'model_name', expected.model, ...
    'simulation_mode', expected.simulation_mode, ...
    'solver', expected.solver, ...
    'sfunction_identity', expected.sfunction_identity, ...
    'sfunction_hash', expected.sfunction_source_sha256, ...
    'sfunction_mex_hash', expected.sfunction_macos_mex_sha256, ...
    'model_hash', expected.model_sha256, ...
    'initial_state_hash', expected.initial_state_sha256, ...
    'case_plan_hash', casePlanHash, ...
    'generation_script_hash', scriptHash, ...
    'output_path', outputPath, ...
    'output_size_bytes', 0, ...
    'output_sha256', '', ...
    'rows', 0, ...
    'cols', 0, ...
    'time_start', NaN, ...
    'time_end', NaN, ...
    'sampling_interval', NaN, ...
    'finite_check', false, ...
    'structural_valid', false, ...
    'technical_failure_reason', '');
end

function observed = inspect_numeric_output(data, expected)
observed = struct( ...
    'rows', size(data, 1), ...
    'cols', size(data, 2), ...
    'time_start', NaN, ...
    'time_end', NaN, ...
    'sampling_interval', NaN, ...
    'finite_check', all(isfinite(data), 'all'), ...
    'structural_valid', false, ...
    'failure_reason', '');
if isempty(data)
    observed.failure_reason = 'numeric output is empty';
    return;
end
time = data(:, 1);
intervals = diff(time);
observed.time_start = time(1);
observed.time_end = time(end);
observed.sampling_interval = intervals(1);
observed.structural_valid = observed.rows == expected.expected_rows && ...
    observed.cols == expected.expected_columns && observed.finite_check && ...
    abs(observed.time_start - expected.start_time_h) <= 1e-10 && ...
    abs(observed.time_end - expected.stop_time_h) <= 1e-10 && ...
    all(intervals > 0) && ...
    all(abs(intervals - expected.sampling_interval_h) <= 1e-10);
if ~observed.structural_valid
    observed.failure_reason = ...
        'shape, finiteness, or Time-axis check failed';
end
end

function verify_written_workbook(path, headers, expectedData, expected)
assert(isfile(path), 'EXP3V2:WorkbookMissing', 'Workbook was not written.');
sheets = sheetnames(path);
assert(isscalar(sheets) && string(sheets(1)) == string(expected.worksheet), ...
    'EXP3V2:WorksheetMismatch', 'Workbook worksheet mismatch.');
observedHeaders = readcell(path, 'Sheet', char(expected.worksheet), ...
    'Range', 'A1:BB1');
assert(isequal(observedHeaders, headers), 'EXP3V2:HeaderMismatch', ...
    'Workbook headers mismatch.');
observedData = readmatrix(path, 'Sheet', char(expected.worksheet), ...
    'Range', 'A2:BB3002');
assert(isequal(observedData, expectedData), ...
    'EXP3V2:WorkbookRoundTripMismatch', ...
    'Workbook numeric content differs after write/read round trip.');
end

function timestamp = utc_timestamp()
value = datetime('now', 'TimeZone', 'UTC', ...
    'Format', "yyyy-MM-dd'T'HH:mm:ss.SSSXXX");
timestamp = char(string(value));
end

function digestHex = sha256_file(path)
assert(isfile(path), 'EXP3V2:HashInputMissing', 'Missing hash input: %s', path);
fid = fopen(path, 'rb');
assert(fid ~= -1, 'EXP3V2:HashInputOpen', 'Cannot open hash input: %s', path);
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid, Inf, 'uint8=>uint8');
digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(bytes);
raw = typecast(digest.digest(), 'uint8');
digestHex = lower(reshape(dec2hex(raw, 2).', 1, []));
end

function value = canonical_path(pathValue)
value = char(java.io.File(pathValue).getCanonicalPath());
end

function result = paths_overlap(left, right)
result = is_within(left, right) || is_within(right, left);
end

function result = is_within(candidate, root)
result = strcmp(candidate, root) || startsWith(candidate, [root filesep]);
end

function close_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end

function cleanup_environment(originalPath, originalDir, modelName)
close_if_loaded(modelName);
close_if_loaded('TElib');
close_if_loaded('tesys');
path(originalPath);
cd(originalDir);
end
