function evidence = sentinel_integration_run(sourceSimulatorDir)
%SENTINEL_INTEGRATION_RUN Run the sole post-harness end-to-end sentinel.
%
% This function is intentionally unreachable until the harness tag exists and
% HEAD is a clean checkout of that tag. It requires an explicit read-only
% external simulator source and never accepts a real case or seed.

assert(nargin == 1 && strlength(string(sourceSimulatorDir)) > 0, ...
    'EXP3V2:ExplicitSimulatorSource', ...
    'Exactly one explicit source simulator directory is required.');
sourceSimulatorDir = canonical_path(char(string(sourceSimulatorDir)));
assert(isfolder(sourceSimulatorDir), 'EXP3V2:SimulatorSourceMissing', ...
    'Explicit source simulator directory does not exist.');

scriptDir = fileparts([mfilename('fullpath') '.m']);
repoRoot = fileparts(fileparts(scriptDir));
harnessPath = fullfile(scriptDir, ...
    'EXP3_V2_HARNESS_FREEZE_MANIFEST_002.json');
harnessManifest = assert_exp3v2_freeze_boundary(harnessPath, ...
    'HARNESS_FROZEN_FOR_SENTINEL', ...
    'exp3-v2-harness-frozen-002', repoRoot);
[statusCode, statusText] = system(sprintf( ...
    'git -C "%s" status --porcelain=v1 --untracked-files=all', repoRoot));
assert(statusCode == 0 && isempty(strtrim(statusText)), ...
    'EXP3V2:SentinelDirtyCheckout', ...
    'Sentinel requires an exactly clean harness-tag checkout.');

realV2Root = fullfile(repoRoot, 'tep_exp3_v2_heldout');
realExp3Root = fullfile(repoRoot, 'tep_exp3_heldout');
before = real_path_snapshot(realV2Root, realExp3Root);
sourceBefore = dependency_source_snapshot(sourceSimulatorDir, harnessManifest);
throwawayDir = tempname;
mkdir(throwawayDir);
validate_throwaway(throwawayDir, realV2Root, realExp3Root);

try
    [fileGenGuard, fileGenState] = configure_exp3v2_file_generation( ...
        throwawayDir, repoRoot, sourceSimulatorDir); %#ok<ASGLU>
    materializerPath = fullfile(scriptDir, ...
        'materialize_exp3v2_runtime.py');
    materializeCommand = sprintf([ ...
        'PYTHONDONTWRITEBYTECODE=1 python3 "%s" --manifest "%s" ' ...
        '--source-simulator-dir "%s" --destination-parent "%s"'], ...
        materializerPath, harnessPath, sourceSimulatorDir, throwawayDir);
    [materializeStatus, materializeOutput] = system(materializeCommand);
    assert(materializeStatus == 0, ...
        'EXP3V2:RuntimeMaterializationFailed', ...
        'External runtime materialization failed: %s', materializeOutput);
    materialization = jsondecode(strtrim(materializeOutput));
    assert(strcmp(materialization.status, 'PASS') && ...
        materialization.dependency_count == ...
        numel(harnessManifest.external_runtime_dependencies), ...
        'EXP3V2:RuntimeMaterializationEvidence', ...
        'External runtime materialization evidence is invalid.');
    runtimeDir = canonical_path(materialization.runtime_dir);
    validate_throwaway(runtimeDir, realV2Root, realExp3Root);
    assert_exp3v2_runtime_bundle(runtimeDir, harnessManifest);

    record = generate_exp3v2_sentinel(throwawayDir, ...
        'SimulatorDir', runtimeDir);
    sentinelManifest = fullfile(throwawayDir, 'sentinel_manifest.csv');
    write_sentinel_manifest(sentinelManifest, record);
    verifierPath = fullfile(scriptDir, 'verify_exp3v2_heldout.py');
    descriptorPath = fullfile(scriptDir, 'exp3v2_sentinel_case.json');
    command = sprintf(['PYTHONDONTWRITEBYTECODE=1 python3 "%s" --sentinel ' ...
        '--sentinel-descriptor "%s" --attempt-log "%s" ' ...
        '--manifest "%s" --data-dir "%s" --harness-manifest "%s" ' ...
        '--runtime-dir "%s"'], ...
        verifierPath, descriptorPath, ...
        fullfile(throwawayDir, 'sentinel_attempt_log.json'), ...
        sentinelManifest, fullfile(throwawayDir, 'mode1'), harnessPath, ...
        runtimeDir);
    [verifierStatus, verifierOutput] = system(command);
    assert(verifierStatus == 0, 'EXP3V2:SentinelVerifierFailed', ...
        'Sentinel verifier failed: %s', verifierOutput);
    assert(test_exp3v2_model_config_management(runtimeDir), ...
        'EXP3V2:InjectedRestorationRegression', ...
        'Injected-error restoration regression failed.');
    assert_saved_model_restored(runtimeDir);
    sourceAfter = dependency_source_snapshot( ...
        sourceSimulatorDir, harnessManifest);
    assert(isequal(sourceBefore, sourceAfter), ...
        'EXP3V2:SimulatorSourceChanged', ...
        'External source simulator directory changed during sentinel.');
    after = real_path_snapshot(realV2Root, realExp3Root);
    assert(isequal(before, after), 'EXP3V2:RealPathInterference', ...
        'Sentinel touched a real attempt log or workbook path.');
    restore_exp3v2_file_generation(fileGenState);
    clear fileGenGuard fileGenState;

    evidence = struct( ...
        'schema_version', '1.0', ...
        'status', 'PASS', ...
        'harness_revision', '002', ...
        'harness_tag', 'exp3-v2-harness-frozen-002', ...
        'harness_commit', git_value(repoRoot, 'rev-parse HEAD'), ...
        'harness_manifest_sha256', sha256_file(harnessPath), ...
        'physical_case_id', 'EXP3V2-SENTINEL-001', ...
        'seed', 987654321, ...
        'rng_algorithm', 'twister', ...
        'runtime', runtime_from_record(record), ...
        'workbook_sha256', record.output_sha256, ...
        'workbook_size_bytes', record.output_size_bytes, ...
        'rows', record.rows, ...
        'cols', record.cols, ...
        'time_axis_check', 'PASS', ...
        'finiteness_check', 'PASS', ...
        'round_trip_check', 'PASS', ...
        'verifier_output', strtrim(verifierOutput), ...
        'stopfcn_restored', true, ...
        'return_workspace_outputs_restored', true, ...
        'dirty_state_restored', true, ...
        'model_sha256_restored', true, ...
        'injected_error_restoration_test', true, ...
        'runtime_materialization', 'PASS', ...
        'source_simulator_unchanged', true, ...
        'file_generation_isolated', true, ...
        'file_generation_configuration_restored', true, ...
        'real_path_non_interference', true, ...
        'throwaway_cleanup', 'PENDING');
    evidence.artifact_hashes = harnessManifest.artifacts;
    evidence.external_runtime_dependencies = ...
        harnessManifest.external_runtime_dependencies;
    validate_throwaway(throwawayDir, realV2Root, realExp3Root);
    rmdir(throwawayDir, 's');
    assert(~isfolder(throwawayDir), 'EXP3V2:SentinelCleanupFailed', ...
        'Validated throwaway directory was not removed.');
    evidence.throwaway_cleanup = 'PASS';
    write_evidence(scriptDir, evidence);
catch exception
    failure = struct( ...
        'schema_version', '1.0', ...
        'status', 'FAIL', ...
        'harness_revision', '002', ...
        'harness_tag', 'exp3-v2-harness-frozen-002', ...
        'harness_commit', git_value(repoRoot, 'rev-parse HEAD'), ...
        'physical_case_id', 'EXP3V2-SENTINEL-001', ...
        'seed', 987654321, ...
        'error_identifier', exception.identifier, ...
        'error_message', exception.message, ...
        'diagnostic_signal_inspected', false, ...
        'real_path_snapshot_before', before, ...
        'real_path_snapshot_after', ...
        real_path_snapshot(realV2Root, realExp3Root));
    write_json(fullfile(scriptDir, ...
        'EXP3_V2_SENTINEL_FAILURE_EVIDENCE.json'), failure);
    rethrow(exception);
end
end

function write_sentinel_manifest(path, record)
fields = {'physical_case_id', 'fault/status', 'attempt', 'seed', ...
    'filename', 'size_bytes', 'SHA256', 'rows', 'cols', 'time_start', ...
    'time_end', 'sampling', 'finite_check', 'structural_valid'};
[~, outputStem, outputExtension] = fileparts(record.output_path);
values = {record.physical_case_id, record.fault_status, record.attempt, ...
    record.seed, [outputStem outputExtension], ...
    record.output_size_bytes, record.output_sha256, record.rows, record.cols, ...
    record.time_start, record.time_end, record.sampling_interval, ...
    record.finite_check, record.structural_valid};
fid = fopen(path, 'w');
assert(fid ~= -1, 'EXP3V2:SentinelManifestOpen', ...
    'Cannot create sentinel manifest.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', strjoin(fields, ','));
fprintf(fid, '%s\n', strjoin(cellfun(@string_value, values, ...
    'UniformOutput', false), ','));
end

function value = string_value(input)
if islogical(input)
    value = lower(char(string(input)));
else
    value = char(string(input));
end
end

function snapshot = real_path_snapshot(v2Root, oldRoot)
snapshot = struct( ...
    'v2_workbook_count', count_workbooks(v2Root), ...
    'old_workbook_count', count_workbooks(oldRoot), ...
    'v2_total_file_count', count_files(v2Root), ...
    'old_total_file_count', count_files(oldRoot), ...
    'v2_attempt_log_sha256', optional_hash( ...
    fullfile(v2Root, 'exp3v2_attempt_log.json')), ...
    'old_attempt_log_sha256', optional_hash( ...
    fullfile(oldRoot, 'exp3_attempt_log.json')));
assert(snapshot.v2_workbook_count == 0 && ...
    snapshot.old_workbook_count == 0, 'EXP3V2:RealWorkbookPresent', ...
    'Sentinel requires zero workbooks in both real output roots.');
end

function count = count_files(root)
if ~isfolder(root)
    count = 0;
    return;
end
files = dir(fullfile(root, '**', '*'));
count = sum(~[files.isdir]);
end

function count = count_workbooks(root)
if ~isfolder(root)
    count = 0;
    return;
end
files = dir(fullfile(root, '**', '*.xlsx'));
count = numel(files);
end

function value = optional_hash(path)
if isfile(path)
    value = sha256_file(path);
else
    value = '';
end
end

function assert_saved_model_restored(runtimeDir)
modelPath = fullfile(runtimeDir, 'MultiLoop_mode1.mdl');
assert(strcmp(sha256_file(modelPath), ...
    'd2f6659f65935021d4b1813e7189be02e7ae9f5639b794e8edc4f2f3c5cddba8'), ...
    'EXP3V2:SentinelModelHash', 'Model bytes changed during sentinel.');
end

function snapshot = dependency_source_snapshot(sourceDir, manifest)
dependencies = manifest.external_runtime_dependencies;
snapshot = struct('path', {}, 'size_bytes', {}, 'sha256', {});
for index = 1:numel(dependencies)
    dependency = dependencies(index);
    path = fullfile(sourceDir, dependency.path);
    assert(isfile(path), 'EXP3V2:SourceDependencyMissing', ...
        'Missing source dependency: %s', dependency.path);
    info = dir(path);
    snapshot(index).path = dependency.path;
    snapshot(index).size_bytes = info.bytes;
    snapshot(index).sha256 = sha256_file(path);
end
end

function validate_throwaway(path, realV2Root, realExp3Root)
path = canonical_path(path);
tempRoot = canonical_path(tempdir);
assert(isfolder(path) && startsWith(path, [tempRoot filesep]), ...
    'EXP3V2:UnsafeThrowaway', ...
    'Throwaway directory must be an existing child of tempdir.');
assert(~paths_overlap(path, canonical_path(realV2Root)) && ...
    ~paths_overlap(path, canonical_path(realExp3Root)), ...
    'EXP3V2:UnsafeThrowawayOverlap', ...
    'Throwaway directory overlaps a real output root.');
end

function write_evidence(scriptDir, evidence)
jsonPath = fullfile(scriptDir, 'EXP3_V2_SENTINEL_EVIDENCE.json');
write_json(jsonPath, evidence);
mdPath = fullfile(scriptDir, 'EXP3_V2_SENTINEL_EVIDENCE.md');
fid = fopen(mdPath, 'w');
assert(fid ~= -1, 'EXP3V2:EvidenceOpen', 'Cannot write sentinel evidence.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Experiment 3 V2 sentinel evidence\n\n');
fprintf(fid, 'Status: PASS\n\n');
fprintf(fid, 'Harness tag/commit: %s / %s\n\n', ...
    evidence.harness_tag, evidence.harness_commit);
fprintf(fid, 'Sentinel: %s, seed %d, twister.\n\n', ...
    evidence.physical_case_id, evidence.seed);
fprintf(fid, ['Structural result: %dx%d, finite PASS, time-axis PASS, ' ...
    'round-trip PASS.\n\n'], evidence.rows, evidence.cols);
fprintf(fid, 'Workbook SHA-256/size: %s / %d bytes.\n\n', ...
    evidence.workbook_sha256, evidence.workbook_size_bytes);
fprintf(fid, ['StopFcn, ReturnWorkspaceOutputs, Dirty state, and model hash ' ...
    'restoration: PASS.\n\n']);
fprintf(fid, 'Real-path non-interference: PASS. Throwaway cleanup: PASS.\n');
end

function write_json(path, value)
fid = fopen(path, 'w');
assert(fid ~= -1, 'EXP3V2:EvidenceJsonOpen', 'Cannot write evidence JSON.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', jsonencode(value, 'PrettyPrint', true));
end

function value = runtime_from_record(record)
value = struct( ...
    'matlab_version_full', record.matlab_version_full, ...
    'matlab_release', record.matlab_release, ...
    'matlab_build', record.matlab_build, ...
    'matlab_product_date', record.matlab_product_date, ...
    'matlab_runtime_update_date', record.matlab_runtime_update_date, ...
    'simulink_version', record.simulink_version, ...
    'simulink_release', record.simulink_release, ...
    'simulink_product_date', record.simulink_product_date, ...
    'architecture', record.architecture, ...
    'matlabroot', record.matlabroot);
end

function value = git_value(repoRoot, arguments)
[status, text] = system(sprintf('git -C "%s" %s', repoRoot, arguments));
assert(status == 0, 'EXP3V2:GitCommand', 'Git command failed: %s', arguments);
value = strtrim(text);
end

function digestHex = sha256_file(path)
fid = fopen(path, 'rb');
assert(fid ~= -1, 'EXP3V2:HashOpen', 'Cannot open hash input: %s', path);
cleanup = onCleanup(@() fclose(fid));
bytes = fread(fid, Inf, 'uint8=>uint8');
digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(bytes);
raw = typecast(digest.digest(), 'uint8');
digestHex = lower(reshape(dec2hex(raw, 2).', 1, []));
end

function value = canonical_path(path)
value = char(java.io.File(path).getCanonicalPath());
end

function result = paths_overlap(left, right)
result = is_within(left, right) || is_within(right, left);
end

function result = is_within(candidate, root)
result = strcmp(candidate, root) || startsWith(candidate, [root filesep]);
end
