function result = test_exp3v2_runtime_provenance()
%TEST_EXP3V2_RUNTIME_PROVENANCE Verify exact runtime semantics without sim.

expected = struct( ...
    'matlab_version_full', '25.2.0.3312555 (R2025b) Update 6', ...
    'matlab_release', '2025b', ...
    'matlab_build', '3312555', ...
    'matlab_product_date', '28-Jul-2025', ...
    'matlab_runtime_update_date', 'June 30, 2026', ...
    'simulink_version', '25.2', ...
    'simulink_release', '(R2025b)', ...
    'simulink_product_date', '28-Jul-2025', ...
    'architecture', 'MACA64', ...
    'matlabroot', '/Applications/MATLAB_R2025b.app');
actual = capture_runtime();
assert_runtime(actual, expected);
fields = {'matlab_version_full', 'matlab_release', 'matlab_build', ...
    'matlab_product_date', 'matlab_runtime_update_date'};
for index = 1:numel(fields)
    changed = actual;
    changed.(fields{index}) = 'wrong';
    assert_identifier(@() assert_runtime(changed, expected), ...
        ['EXP3V2:' fields{index}]);
end
result = true;
fprintf('PASS: V2 five-field runtime semantics accepted/rejected exactly.\n');
end

function runtime = capture_runtime()
matlabProduct = ver('MATLAB'); %#ok<VERMATLAB>
simulinkProduct = ver('Simulink');
exactVersion = version;
buildToken = regexp(exactVersion, '\.(\d+) \(R\d{4}[ab]\)', ...
    'tokens', 'once');
assert(~isempty(buildToken), 'EXP3V2:MatlabBuildUnavailable', ...
    'Could not parse MATLAB build.');
runtime = struct( ...
    'matlab_version_full', exactVersion, ...
    'matlab_release', version('-release'), ...
    'matlab_build', buildToken{1}, ...
    'matlab_product_date', matlabProduct.Date, ...
    'matlab_runtime_update_date', version('-date'), ...
    'simulink_version', simulinkProduct.Version, ...
    'simulink_release', simulinkProduct.Release, ...
    'simulink_product_date', simulinkProduct.Date, ...
    'architecture', computer, 'matlabroot', matlabroot);
end

function assert_runtime(actual, expected)
fields = fieldnames(expected);
for index = 1:numel(fields)
    field = fields{index};
    assert(strcmp(actual.(field), expected.(field)), ...
        ['EXP3V2:' field], 'Runtime mismatch: %s', field);
end
end

function assert_identifier(operation, expected)
observed = '';
try
    operation();
catch exception
    observed = exception.identifier;
end
assert(strcmp(observed, expected), 'EXP3V2:RegressionIdentifier', ...
    'Expected %s, observed %s.', expected, observed);
end
