function result = test_exp3v2_csv_serialization()
%TEST_EXP3V2_CSV_SERIALIZATION Verify round-trip-safe manifest scalars.

sampling = format_exp3v2_csv_scalar(1 / 60);
assert(strcmp(sampling, '0.016666666666666666'));
assert(~strcmp(sampling, '0.016667'));
assert(isequal(str2double(sampling), 1 / 60));
assert(strcmp(format_exp3v2_csv_scalar(987654322), '987654322'));
assert(strcmp(format_exp3v2_csv_scalar(3001), '3001'));
assert(strcmp(format_exp3v2_csv_scalar(true), 'true'));
assert(strcmp(format_exp3v2_csv_scalar(false), 'false'));

manifestPath = [tempname '.csv'];
cleanup = onCleanup(@() delete_if_present(manifestPath));
record = struct( ...
    'physical_case_id', 'EXP3V2-SENTINEL-002', ...
    'fault_status', 'Normal', ...
    'attempt', 0, ...
    'seed', 987654322, ...
    'output_path', fullfile(tempdir, ...
    'EXP3V2-SENTINEL-002__attempt-0.xlsx'), ...
    'output_size_bytes', 1704651, ...
    'output_sha256', repmat('a', 1, 64), ...
    'rows', 3001, ...
    'cols', 54, ...
    'time_start', 0, ...
    'time_end', 50, ...
    'sampling_interval', 1 / 60, ...
    'finite_check', true, ...
    'structural_valid', true);
write_exp3v2_sentinel_manifest(manifestPath, record);
lines = splitlines(string(fileread(manifestPath)));
fields = split(lines(2), ',');
assert(strcmp(fields(12), sampling));
assert(strcmp(fields(13), 'true') && strcmp(fields(14), 'true'));

result = true;
fprintf('PASS: sentinel CSV numeric serialization is binary64 round-trip-safe.\n');
clear cleanup;
end

function delete_if_present(path)
if isfile(path)
    delete(path);
end
end
