function result = test_exp3v2_output_retrieval()
%TEST_EXP3V2_OUTPUT_RETRIEVAL Regress incident 5 without calling sim.

assert_identifier(@() extract_exp3v2_outputs(42, 3001), ...
    'EXP3V2:SimulationOutputType');
source = fileread(fullfile(fileparts([mfilename('fullpath') '.m']), ...
    'extract_exp3v2_outputs.m'));
required = { ...
    'Simulink.SimulationOutput', ...
    'who(simResult)', ...
    'simResult.get(''tout'')', ...
    'simResult.get(''simout'')', ...
    'simResult.get(''xmv'')', ...
    '[expectedRows 1]', '[expectedRows 41]', '[expectedRows 12]'};
for index = 1:numel(required)
    assert(contains(source, required{index}), ...
        'EXP3V2:OutputContractMissing', ...
        'Missing output-retrieval contract token: %s', required{index});
end
assert(~contains(source, 'evalin'), 'EXP3V2:BaseFallbackPresent', ...
    'Output extraction must not read the base workspace.');
result = true;
fprintf(['PASS: non-SimulationOutput rejected; typed tout/simout/xmv ' ...
    '3001x54 contract present; sim not called.\n']);
end

function assert_identifier(operation, expected)
observed = '';
try
    operation();
catch exception
    observed = exception.identifier;
end
assert(strcmp(observed, expected), 'EXP3V2:RegressionIdentifier', ...
    'Expected %s, observed %s.', expected, observed);
end
