function runtime = validate_exp3v2_python_runtime(pythonExecutable)
%VALIDATE_EXP3V2_PYTHON_RUNTIME Fail closed on the pinned Python runtime.

assert((ischar(pythonExecutable) && isrow(pythonExecutable)) || ...
    (isstring(pythonExecutable) && isscalar(pythonExecutable)), ...
    'EXP3V2:PythonExecutableType', ...
    'Python executable must be a character vector or string scalar.');
pythonExecutable = char(pythonExecutable);
inputFile = java.io.File(pythonExecutable);
assert(inputFile.isAbsolute(), 'EXP3V2:PythonExecutableNotAbsolute', ...
    'Python executable must be supplied as an absolute path.');
canonicalExecutable = char(inputFile.getCanonicalPath());
resolvedFile = java.io.File(canonicalExecutable);
assert(resolvedFile.isFile(), 'EXP3V2:PythonExecutableNotRegular', ...
    'Python executable must resolve to a regular file.');
assert(resolvedFile.canExecute(), 'EXP3V2:PythonExecutableNotExecutable', ...
    'Python executable must resolve to an executable file.');

probe = [ ...
    'import importlib.metadata as metadata, json, os, sys;' ...
    'import jsonschema, openpyxl;' ...
    'print(json.dumps({' ...
    '"executable": os.path.realpath(sys.executable),' ...
    '"python_version": ".".join(map(str, sys.version_info[:3])),' ...
    '"jsonschema_version": metadata.version("jsonschema"),' ...
    '"openpyxl_version": metadata.version("openpyxl")' ...
    '}))'];
command = sprintf('PYTHONDONTWRITEBYTECODE=1 %s -c %s', ...
    exp3v2_shell_quote(canonicalExecutable), exp3v2_shell_quote(probe));
[status, output] = system(command);
assert(status == 0, 'EXP3V2:PythonRuntimeProbeFailed', ...
    'Python runtime/dependency probe failed: %s', strtrim(output));
try
    observed = jsondecode(strtrim(output));
catch exception
    error('EXP3V2:PythonRuntimeProbeInvalid', ...
        'Python runtime probe did not return valid JSON: %s', exception.message);
end

assert(strcmp(char(observed.python_version), '3.13.9'), ...
    'EXP3V2:PythonVersionMismatch', ...
    'Python version must be exactly 3.13.9.');
assert(strcmp(char(observed.jsonschema_version), '4.25.0'), ...
    'EXP3V2:JsonschemaVersionMismatch', ...
    'jsonschema version must be exactly 4.25.0.');
assert(strcmp(char(observed.openpyxl_version), '3.1.5'), ...
    'EXP3V2:OpenpyxlVersionMismatch', ...
    'openpyxl version must be exactly 3.1.5.');
reportedExecutable = char(java.io.File( ...
    char(observed.executable)).getCanonicalPath());
assert(strcmp(reportedExecutable, canonicalExecutable), ...
    'EXP3V2:PythonExecutableMismatch', ...
    'The probed interpreter differs from the resolved executable.');

runtime = struct( ...
    'executable_path', canonicalExecutable, ...
    'python_version', char(observed.python_version), ...
    'jsonschema_version', char(observed.jsonschema_version), ...
    'openpyxl_version', char(observed.openpyxl_version));
end
