function write_exp3v2_sentinel_manifest(path, record)
%WRITE_EXP3V2_SENTINEL_MANIFEST Write one round-trip-safe sentinel row.

fields = {'physical_case_id', 'fault/status', 'attempt', 'seed', ...
    'filename', 'size_bytes', 'SHA256', 'rows', 'cols', 'time_start', ...
    'time_end', 'sampling', 'finite_check', 'structural_valid'};
[~, outputStem, outputExtension] = fileparts(record.output_path);
values = {record.physical_case_id, record.fault_status, record.attempt, ...
    record.seed, [outputStem outputExtension], ...
    record.output_size_bytes, record.output_sha256, record.rows, record.cols, ...
    record.time_start, record.time_end, record.sampling_interval, ...
    record.finite_check, record.structural_valid};
fid = fopen(path, 'w');
assert(fid ~= -1, 'EXP3V2:SentinelManifestOpen', ...
    'Cannot create sentinel manifest.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', strjoin(fields, ','));
fprintf(fid, '%s\n', strjoin(cellfun(@format_exp3v2_csv_scalar, values, ...
    'UniformOutput', false), ','));
end
