function record = generate_exp3_heldout(physicalCaseId, attempt, varargin)
%GENERATE_EXP3_HELDOUT Generate one pre-specified Experiment 3 attempt.
%
% This function is intentionally single-case and fail-closed. It reads the
% machine-readable case plan, enforces the one-replacement policy, runs the
% frozen Mode 1 simulator, performs structural checks only, writes one XLSX,
% and appends complete technical provenance to the attempt log.
%
% It does not inspect fault strength, calculate diagnostic features, invoke a
% verbalizer or LLM, or make any scientific selection decision.

parser = inputParser;
parser.addRequired('physicalCaseId', @(x) ischar(x) || isstring(x));
parser.addRequired('attempt', @(x) isnumeric(x) && isscalar(x) && ismember(x, [0 1]));
parser.addParameter('CasePlanPath', '', @(x) ischar(x) || isstring(x));
parser.addParameter('FreezeManifestPath', '', @(x) ischar(x) || isstring(x));
parser.addParameter('HotfixManifestPath', '', @(x) ischar(x) || isstring(x));
parser.addParameter('OutputDir', '', @(x) ischar(x) || isstring(x));
parser.addParameter('AttemptLogPath', '', @(x) ischar(x) || isstring(x));
parser.addParameter('SimulatorDir', '', @(x) ischar(x) || isstring(x));
parser.parse(physicalCaseId, attempt, varargin{:});

physicalCaseId = char(string(parser.Results.physicalCaseId));
attempt = double(parser.Results.attempt);
scriptPath = [mfilename('fullpath') '.m'];
scriptDir = fileparts(scriptPath);
repoRoot = fileparts(fileparts(scriptDir));

casePlanPath = default_path(parser.Results.CasePlanPath, ...
    fullfile(scriptDir, 'exp3_case_plan.json'));
freezeManifestPath = default_path(parser.Results.FreezeManifestPath, ...
    fullfile(scriptDir, 'EXP3_FREEZE_MANIFEST.json'));
hotfixManifestPath = default_path(parser.Results.HotfixManifestPath, ...
    fullfile(scriptDir, 'EXP3_POST_FREEZE_HOTFIX_002.json'));
outputDir = default_path(parser.Results.OutputDir, ...
    fullfile(repoRoot, 'tep_exp3_heldout', 'mode1'));
attemptLogPath = default_path(parser.Results.AttemptLogPath, ...
    fullfile(repoRoot, 'tep_exp3_heldout', 'exp3_attempt_log.json'));
simulatorDir = default_path(parser.Results.SimulatorDir, ...
    fullfile(repoRoot, 'tep_parent_a0413e16', 'simulator'));

plan = jsondecode(fileread(casePlanPath));
assert_plan_constants(plan);
freezeManifest = jsondecode(fileread(freezeManifestPath));
assert(strcmp(freezeManifest.status, 'FROZEN_BEFORE_GENERATION'), ...
    'EXP3:FreezeManifestStatus', 'Freeze manifest status mismatch.');
assert(strcmp(freezeManifest.hash_algorithm, 'SHA-256'), ...
    'EXP3:FreezeManifestAlgorithm', 'Freeze manifest hash algorithm mismatch.');
assert(strcmp(freezeManifest.freeze_tag, 'exp3-heldout-frozen'), ...
    'EXP3:FreezeManifestTag', 'Freeze manifest tag mismatch.');
hotfixManifest = jsondecode(fileread(hotfixManifestPath));
assert(strcmp(hotfixManifest.hotfix_id, 'EXP3_POST_FREEZE_HOTFIX_002') && ...
    strcmp(hotfixManifest.status, 'AUTHORIZED_BEFORE_FIRST_SIMULATION'), ...
    'EXP3:HotfixManifestStatus', 'Hotfix manifest identity/status mismatch.');
assert(strcmp(hotfixManifest.original_freeze_commit, ...
    'b02e93f92bf6fa85a4fd0a2e010bac365a3a7c89') && ...
    strcmp(hotfixManifest.original_freeze_tag, 'exp3-heldout-frozen') && ...
    strcmp(hotfixManifest.hotfix_001_commit, ...
    'cdba0202435d1c97ea79cfff586e59534ce9baad') && ...
    ~hotfixManifest.scientific_protocol_changed && ...
    ~hotfixManifest.experiment_1_frozen_artifacts_changed, ...
    'EXP3:HotfixBoundaryMismatch', ...
    'Hotfix record does not preserve the frozen scientific boundary.');
hotfix001Path = fullfile(scriptDir, 'EXP3_POST_FREEZE_HOTFIX_001.json');
hotfix001 = jsondecode(fileread(hotfix001Path));
caseEntry = select_case(plan.cases, physicalCaseId);
assert(caseEntry.max_total_attempts == 2, ...
    'EXP3:PolicyMismatch', 'max_total_attempts must equal 2.');

if attempt == 0
    seed = double(caseEntry.primary_seed);
else
    seed = double(caseEntry.replacement_seed);
end

attemptLog = read_attempt_log(attemptLogPath);
assert_attempt_allowed(attemptLog, physicalCaseId, attempt, seed, caseEntry);

if ~isfolder(outputDir)
    mkdir(outputDir);
end
outputFilename = sprintf('%s__attempt-%d.xlsx', physicalCaseId, attempt);
outputPath = fullfile(outputDir, outputFilename);
assert(~isfile(outputPath), 'EXP3:RefuseOverwrite', ...
    'Refusing to overwrite existing output: %s', outputPath);

expected = plan.simulator;
modelName = char(expected.model);
modelPath = fullfile(simulatorDir, [modelName '.mdl']);
initialStatePath = fullfile(simulatorDir, char(expected.initial_state_file));
sfunctionSourcePath = fullfile(simulatorDir, 'temexd_mod.c');
sfunctionMexPath = fullfile(simulatorDir, 'temexd_mod.mexmaca64');

assert(strcmp(sha256_file(modelPath), char(expected.model_sha256)), ...
    'EXP3:ModelHashMismatch', 'Simulator model hash mismatch.');
assert(strcmp(sha256_file(initialStatePath), char(expected.initial_state_sha256)), ...
    'EXP3:InitialStateHashMismatch', 'Initial-state file hash mismatch.');
assert(strcmp(sha256_file(sfunctionSourcePath), ...
    char(expected.sfunction_source_sha256)), ...
    'EXP3:SFunctionSourceHashMismatch', 'S-function source hash mismatch.');
assert(strcmp(sha256_file(sfunctionMexPath), ...
    char(expected.sfunction_macos_mex_sha256)), ...
    'EXP3:SFunctionMexHashMismatch', 'S-function MEX hash mismatch.');

generationScriptHash = sha256_file(scriptPath);
casePlanHash = sha256_file(casePlanPath);
originalGeneratorHash = frozen_hash(freezeManifest, ...
    'phase_b/exp3/generate_exp3_heldout.m');
assert(strcmp(sha256_file(freezeManifestPath), ...
    char(hotfixManifest.original_freeze_manifest_sha256)), ...
    'EXP3:HotfixFreezeManifestHashMismatch', ...
    'Original freeze manifest hash differs from the hotfix record.');
assert(strcmp(originalGeneratorHash, ...
    char(hotfixManifest.frozen_original_generator_sha256)), ...
    'EXP3:HotfixOriginalHashMismatch', ...
    'Hotfix record does not match the frozen original generator hash.');
assert(strcmp(sha256_file(hotfix001Path), ...
    char(hotfixManifest.hotfix_001_manifest_sha256)) && ...
    strcmp(char(hotfix001.hotfix_id), 'EXP3_POST_FREEZE_HOTFIX_001') && ...
    strcmp(char(hotfix001.hotfixed_generator_sha256), ...
    char(hotfixManifest.hotfix_001_generator_sha256)), ...
    'EXP3:HotfixChainMismatch', ...
    'Hotfix 001 provenance does not match the authorized hotfix chain.');
assert(strcmp(generationScriptHash, ...
    char(hotfixManifest.hotfix_002_generator_sha256)), ...
    'EXP3:GenerationScriptNotFrozen', ...
    'Generation script hash differs from the authorized hotfix hash.');
assert(strcmp(frozen_hash(freezeManifest, ...
    'phase_b/exp3/exp3_case_plan.json'), ...
    char(hotfixManifest.frozen_original_case_plan_sha256)), ...
    'EXP3:HotfixOriginalCasePlanHashMismatch', ...
    'Hotfix record does not match the frozen original case-plan hash.');
assert(strcmp(casePlanHash, ...
    char(hotfixManifest.hotfix_002_case_plan_sha256)), ...
    'EXP3:HotfixCasePlanHashMismatch', ...
    'Case-plan hash differs from the authorized provenance hotfix hash.');
runtime = capture_runtime();
assert_runtime(runtime, plan.runtime);

startedAt = utc_timestamp();
record = empty_record(physicalCaseId, char(caseEntry.condition), attempt, seed, ...
    runtime, char(expected.simulator_commit), modelName, ...
    char(expected.simulation_mode), char(expected.solver), ...
    char(expected.sfunction_identity), char(expected.sfunction_source_sha256), ...
    char(expected.sfunction_macos_mex_sha256), char(expected.model_sha256), ...
    char(expected.initial_state_sha256), casePlanHash, generationScriptHash, ...
    outputPath, startedAt);

originalPath = path;
originalDir = pwd;
cleanup = onCleanup(@() cleanup_environment(originalPath, originalDir, modelName));

try
    addpath(simulatorDir, '-begin');
    cd(simulatorDir);
    rehash;

    close_if_loaded(modelName);
    close_if_loaded('TElib');
    close_if_loaded('tesys');

    % load_system executes PreLoadFcn -> Mode_1_Init -> load Mode1xInitial.
    load_system(modelName);
    assert(strcmp(get_param(modelName, 'FileName'), modelPath), ...
        'EXP3:WrongModelPath', 'Loaded model path does not match the pinned model.');
    assert(strcmp(get_param(modelName, 'SimulationMode'), ...
        char(expected.simulation_mode)), 'EXP3:SimulationModeMismatch', ...
        'Simulation mode mismatch.');
    assert(strcmp(get_param(modelName, 'Solver'), char(expected.solver)), ...
        'EXP3:SolverMismatch', 'Solver mismatch.');
    assert(str2double(get_param(modelName, 'StartTime')) == expected.start_time_h, ...
        'EXP3:StartTimeMismatch', 'Start time mismatch.');
    assert(str2double(get_param(modelName, 'StopTime')) == expected.stop_time_h, ...
        'EXP3:StopTimeMismatch', 'Stop time mismatch.');
    assert(strcmp(get_param(modelName, 'LoadInitialState'), 'on'), ...
        'EXP3:InitialStateDisabled', 'LoadInitialState must be on.');
    assert(strcmp(get_param(modelName, 'InitialState'), 'xInitial'), ...
        'EXP3:InitialStateNameMismatch', 'InitialState must be xInitial.');
    assert(strcmp(strtrim(get_param(modelName, 'PreLoadFcn')), 'Mode_1_Init'), ...
        'EXP3:PreLoadCallbackMismatch', 'PreLoadFcn must be Mode_1_Init.');
    assert(strcmp(strtrim(get_param(modelName, 'StopFcn')), 'TEplot'), ...
        'EXP3:StopCallbackMismatch', 'StopFcn must be TEplot.');
    assert(evalin('base', "exist('xInitial','var') == 1"), ...
        'EXP3:InitialStateMissing', ...
        'Mode1xInitial did not provide xInitial in the base workspace.');

    teBlocks = find_system(modelName, 'LookUnderMasks', 'all', ...
        'FollowLinks', 'on', 'Name', 'TE Code');
    assert(isscalar(teBlocks), 'EXP3:SFunctionBlockCount', ...
        'Expected exactly one TE Code block.');
    assert(strcmp(get_param(teBlocks{1}, 'FunctionName'), ...
        char(expected.sfunction_identity)), 'EXP3:SFunctionIdentityMismatch', ...
        'S-function identity mismatch.');
    assert(strcmp(strtrim(get_param(teBlocks{1}, 'Parameters')), '[] rand()'), ...
        'EXP3:SFunctionParametersMismatch', ...
        'S-function parameters must remain exactly [] rand().');

    % Configure the physical condition after Mode_1_Init has completed.
    dist = zeros(1, 28);
    if ~strcmp(char(caseEntry.condition), 'Normal')
        faultIndex = sscanf(char(caseEntry.condition), 'F%d');
        assert(ismember(faultIndex, [1 8 10 13]), ...
            'EXP3:UnexpectedFault', 'Unexpected fault condition.');
        dist(faultIndex) = 1;
    end
    assignin('base', 'dist', dist);

    % PROTOCOL-CRITICAL: rng is the final random-relevant operation before sim.
    rng(seed, 'twister');
    simResult = sim(modelName);

    availableOutputs = string(simResult.who);
    if all(ismember(["tout" "simout" "xmv"], availableOutputs))
        tout = simResult.get('tout');
        simout = simResult.get('simout');
        xmv = simResult.get('xmv');
    else
        assert(evalin('base', ...
            "exist('tout','var') && exist('simout','var') && exist('xmv','var')"), ...
            'EXP3:WorkspaceOutputsMissing', ...
            'Expected tout, simout, and xmv workspace outputs are missing.');
        tout = evalin('base', 'tout');
        simout = evalin('base', 'simout');
        xmv = evalin('base', 'xmv');
    end
    numericOutput = [double(tout), double(simout), double(xmv)];

    observed = inspect_numeric_output(numericOutput, expected);
    if ~observed.structural_valid
        error('EXP3:StructuralInvalid', '%s', observed.failure_reason);
    end

    headers = [{'Time (h)'}, ...
        arrayfun(@(i) sprintf('XMEAS-%d', i), 1:41, 'UniformOutput', false), ...
        arrayfun(@(i) sprintf('XMV-%d', i), 1:12, 'UniformOutput', false)];
    writecell(headers, outputPath, 'Sheet', char(expected.worksheet), 'Range', 'A1');
    writematrix(numericOutput, outputPath, 'Sheet', char(expected.worksheet), ...
        'Range', 'A2');

    verify_written_workbook(outputPath, headers, numericOutput, expected);
    fileInfo = dir(outputPath);

    record.completed_at = utc_timestamp();
    record.output_size_bytes = fileInfo.bytes;
    record.output_sha256 = sha256_file(outputPath);
    record.rows = observed.rows;
    record.cols = observed.cols;
    record.time_start = observed.time_start;
    record.time_end = observed.time_end;
    record.sampling_interval = observed.sampling_interval;
    record.finite_check = observed.finite_check;
    record.structural_valid = true;
    record.technical_failure_reason = '';
    append_attempt_record(attemptLogPath, attemptLog, record);
catch exception
    record.completed_at = utc_timestamp();
    record.technical_failure_reason = sprintf('%s: %s', ...
        exception.identifier, exception.message);
    if isfile(outputPath)
        fileInfo = dir(outputPath);
        record.output_size_bytes = fileInfo.bytes;
        record.output_sha256 = sha256_file(outputPath);
    end
    append_attempt_record(attemptLogPath, attemptLog, record);
    rethrow(exception);
end
end

function value = default_path(provided, fallback)
if strlength(string(provided)) == 0
    value = fallback;
else
    value = char(string(provided));
end
end

function value = frozen_hash(manifest, relativePath)
artifacts = manifest.artifacts;
paths = string({artifacts.path});
index = find(paths == string(relativePath));
assert(isscalar(index), 'EXP3:FreezeManifestLookup', ...
    'Freeze manifest must contain exactly one entry for %s.', relativePath);
value = char(artifacts(index).sha256);
assert(~isempty(regexp(value, '^[0-9a-f]{64}$', 'once')), ...
    'EXP3:FreezeManifestHash', 'Invalid frozen SHA-256 for %s.', relativePath);
end

function assert_plan_constants(plan)
assert(strcmp(plan.status, 'FROZEN_BEFORE_GENERATION'), 'EXP3:PlanNotFrozen', ...
    ['Generation is disabled until the audited case plan status is ' ...
    'FROZEN_BEFORE_GENERATION.']);
assert(strcmp(plan.rng.algorithm, 'twister'), 'EXP3:RngAlgorithm', ...
    'RNG algorithm must be twister.');
assert(plan.rng.max_total_attempts == 2, 'EXP3:MaxAttempts', ...
    'Exactly two total attempts are allowed.');
assert(isequal(double(plan.rng.allowed_attempts(:))', [0 1]), ...
    'EXP3:AllowedAttempts', 'Allowed attempts must be [0,1].');
assert(plan.rng.bootstrap_seed == 310031, 'EXP3:BootstrapSeed', ...
    'Bootstrap seed mismatch.');
assert(numel(plan.cases) == 30, 'EXP3:CaseCount', ...
    'Case plan must contain exactly 30 cases.');
conditions = {'Normal', 'F1', 'F8', 'F10', 'F13'};
ordinal = 0;
allPrimary = zeros(1, 30);
allReplacement = zeros(1, 30);
for conditionIndex = 1:numel(conditions)
    condition = conditions{conditionIndex};
    if strcmp(condition, 'Normal')
        prefix = 'N';
    else
        prefix = condition;
    end
    for runIndex = 1:6
        ordinal = ordinal + 1;
        entry = plan.cases(ordinal);
        expectedId = sprintf('EXP3-%s-%03d', prefix, runIndex);
        expectedPrimary = 310000 + ordinal;
        assert(strcmp(entry.physical_case_id, expectedId), ...
            'EXP3:CasePlanId', 'Case-plan ID/order mismatch.');
        assert(strcmp(entry.condition, condition) && ...
            entry.run_index == runIndex, 'EXP3:CasePlanCondition', ...
            'Case-plan condition/run-index mismatch.');
        assert(strcmp(entry.rng_algorithm, 'twister'), ...
            'EXP3:CasePlanAlgorithm', 'Case RNG algorithm mismatch.');
        assert(entry.primary_seed == expectedPrimary && ...
            entry.replacement_seed == expectedPrimary + 1000000, ...
            'EXP3:CasePlanSeed', 'Case seed mapping mismatch.');
        assert(entry.max_total_attempts == 2, 'EXP3:CasePlanAttempts', ...
            'Case max_total_attempts mismatch.');
        allPrimary(ordinal) = entry.primary_seed;
        allReplacement(ordinal) = entry.replacement_seed;
    end
end
assert(numel(unique(allPrimary)) == 30 && ...
    numel(unique(allReplacement)) == 30 && ...
    isempty(intersect(allPrimary, allReplacement)), ...
    'EXP3:CasePlanCollision', 'Case-plan seed collision detected.');

expected = plan.simulator;
assert(strcmp(expected.simulator_commit, ...
    'a0413e16c940f0fc8b554d6a86248020d7fb7527'), ...
    'EXP3:SimulatorCommit', 'Simulator commit mismatch.');
assert(strcmp(expected.model, 'MultiLoop_mode1') && ...
    strcmp(expected.tep_mode, 'Mode 1') && ...
    strcmp(expected.simulation_mode, 'normal') && ...
    strcmp(expected.solver, 'ode45'), 'EXP3:SimulatorConfiguration', ...
    'Model, mode, simulation mode, or solver mismatch.');
assert(expected.start_time_h == 0 && expected.stop_time_h == 50 && ...
    abs(expected.sampling_interval_h - 1/60) <= 1e-15 && ...
    expected.fault_injection_h == 10, 'EXP3:TimeConfiguration', ...
    'Simulator time configuration mismatch.');
assert(~expected.custom_setpoints && expected.expected_rows == 3001 && ...
    expected.expected_columns == 54 && strcmp(expected.worksheet, 'Sheet1'), ...
    'EXP3:OutputConfiguration', 'Output configuration mismatch.');
end

function entry = select_case(cases, physicalCaseId)
ids = string({cases.physical_case_id});
index = find(ids == string(physicalCaseId));
assert(isscalar(index), 'EXP3:CaseLookup', ...
    'physical_case_id must match exactly one planned case.');
entry = cases(index);
end

function log = read_attempt_log(path)
if isfile(path)
    log = jsondecode(fileread(path));
else
    log = struct( ...
        'schema_version', '1.0', ...
        'experiment', 'Experiment 3 — Fresh Prospective Physical-Run Extension', ...
        'attempts', []);
end
assert(strcmp(log.schema_version, '1.0'), 'EXP3:AttemptLogSchema', ...
    'Attempt log schema version mismatch.');
end

function assert_attempt_allowed(log, caseId, attempt, seed, caseEntry)
attempts = log.attempts;
if isempty(attempts)
    prior = struct('attempt', {}, 'structural_valid', {}, ...
        'technical_failure_reason', {});
else
    prior = attempts(strcmp({attempts.physical_case_id}, caseId));
end
assert(~any([prior.attempt] == attempt), 'EXP3:DuplicateAttempt', ...
    'This case/attempt is already present in the attempt log.');
if attempt == 0
    assert(seed == caseEntry.primary_seed, 'EXP3:PrimarySeedMismatch', ...
        'Attempt 0 must use the primary seed.');
else
    assert(seed == caseEntry.replacement_seed, 'EXP3:ReplacementSeedMismatch', ...
        'Attempt 1 must use the replacement seed.');
    primary = prior([prior.attempt] == 0);
    assert(isscalar(primary), 'EXP3:ReplacementWithoutPrimary', ...
        'Attempt 1 requires exactly one logged attempt 0.');
    assert(~primary.structural_valid && ...
        strlength(string(primary.technical_failure_reason)) > 0, ...
        'EXP3:UnauthorizedReplacement', ...
        'Attempt 1 requires a technical failure on attempt 0.');
end
assert(numel(prior) < 2, 'EXP3:AttemptLimit', ...
    'Maximum two total attempts per intended case.');
end

function runtime = capture_runtime()
matlabProduct = ver('MATLAB'); %#ok<VERMATLAB>
simulinkProduct = ver('Simulink');
exactVersion = version;
buildToken = regexp(exactVersion, '\.(\d+) \(R\d{4}[ab]\)', 'tokens', 'once');
assert(~isempty(buildToken), 'EXP3:MatlabBuildUnavailable', ...
    'Could not parse MATLAB build from version string.');
runtime = struct( ...
    'matlab_version_full', exactVersion, ...
    'matlab_release', version('-release'), ...
    'matlab_build', buildToken{1}, ...
    'matlab_product_date', matlabProduct.Date, ...
    'matlab_runtime_update_date', version('-date'), ...
    'simulink_version', simulinkProduct.Version, ...
    'simulink_release', simulinkProduct.Release, ...
    'simulink_product_date', simulinkProduct.Date, ...
    'architecture', computer, ...
    'matlabroot', matlabroot);
end

function assert_runtime(actual, expected)
assert(strcmp(actual.matlab_version_full, expected.matlab_version_full), ...
    'EXP3:MatlabVersionMismatch', 'MATLAB exact version mismatch.');
assert(strcmp(actual.matlab_release, expected.matlab_release), ...
    'EXP3:MatlabReleaseMismatch', 'MATLAB release mismatch.');
assert(strcmp(actual.matlab_build, expected.matlab_build), ...
    'EXP3:MatlabBuildMismatch', 'MATLAB build mismatch.');
assert(strcmp(actual.matlab_product_date, expected.matlab_product_date), ...
    'EXP3:MatlabProductDateMismatch', 'MATLAB product date mismatch.');
assert(strcmp(actual.matlab_runtime_update_date, ...
    expected.matlab_runtime_update_date), ...
    'EXP3:MatlabRuntimeUpdateDateMismatch', ...
    'MATLAB runtime/update date mismatch.');
assert(strcmp(actual.simulink_version, expected.simulink_version), ...
    'EXP3:SimulinkVersionMismatch', 'Simulink version mismatch.');
assert(strcmp(actual.simulink_release, expected.simulink_release), ...
    'EXP3:SimulinkReleaseMismatch', 'Simulink release mismatch.');
assert(strcmp(actual.simulink_product_date, expected.simulink_product_date), ...
    'EXP3:SimulinkDateMismatch', 'Simulink product date mismatch.');
assert(strcmp(actual.architecture, expected.architecture), ...
    'EXP3:ArchitectureMismatch', 'Architecture mismatch.');
assert(strcmp(actual.matlabroot, expected.matlabroot), ...
    'EXP3:MatlabRootMismatch', 'matlabroot mismatch.');
end

function record = empty_record(caseId, faultStatus, attempt, seed, runtime, ...
        simulatorCommit, modelName, simulationMode, solver, sfunctionIdentity, ...
        sfunctionHash, sfunctionMexHash, modelHash, initialStateHash, ...
        casePlanHash, scriptHash, outputPath, startedAt)
record = struct( ...
    'physical_case_id', caseId, ...
    'fault_status', faultStatus, ...
    'attempt', attempt, ...
    'seed', seed, ...
    'rng_algorithm', 'twister', ...
    'started_at', startedAt, ...
    'completed_at', '', ...
    'matlab_version_full', runtime.matlab_version_full, ...
    'matlab_release', runtime.matlab_release, ...
    'matlab_build', runtime.matlab_build, ...
    'matlab_product_date', runtime.matlab_product_date, ...
    'matlab_runtime_update_date', runtime.matlab_runtime_update_date, ...
    'simulink_version', runtime.simulink_version, ...
    'simulink_release', runtime.simulink_release, ...
    'simulink_product_date', runtime.simulink_product_date, ...
    'architecture', runtime.architecture, ...
    'matlabroot', runtime.matlabroot, ...
    'simulator_commit', simulatorCommit, ...
    'model_name', modelName, ...
    'simulation_mode', simulationMode, ...
    'solver', solver, ...
    'sfunction_identity', sfunctionIdentity, ...
    'sfunction_hash', sfunctionHash, ...
    'sfunction_mex_hash', sfunctionMexHash, ...
    'model_hash', modelHash, ...
    'initial_state_hash', initialStateHash, ...
    'case_plan_hash', casePlanHash, ...
    'generation_script_hash', scriptHash, ...
    'output_path', outputPath, ...
    'output_size_bytes', 0, ...
    'output_sha256', '', ...
    'rows', 0, ...
    'cols', 0, ...
    'time_start', NaN, ...
    'time_end', NaN, ...
    'sampling_interval', NaN, ...
    'finite_check', false, ...
    'structural_valid', false, ...
    'technical_failure_reason', '');
end

function observed = inspect_numeric_output(data, expected)
observed = struct( ...
    'rows', size(data, 1), ...
    'cols', size(data, 2), ...
    'time_start', NaN, ...
    'time_end', NaN, ...
    'sampling_interval', NaN, ...
    'finite_check', all(isfinite(data), 'all'), ...
    'structural_valid', false, ...
    'failure_reason', '');
if isempty(data)
    observed.failure_reason = 'numeric output is empty';
    return;
end
time = data(:, 1);
intervals = diff(time);
observed.time_start = time(1);
observed.time_end = time(end);
observed.sampling_interval = intervals(1);
checks = [ ...
    observed.rows == expected.expected_rows, ...
    observed.cols == expected.expected_columns, ...
    observed.finite_check, ...
    abs(observed.time_start - expected.start_time_h) <= 1e-10, ...
    abs(observed.time_end - expected.stop_time_h) <= 1e-10, ...
    all(intervals > 0), ...
    all(abs(intervals - expected.sampling_interval_h) <= 1e-10)];
observed.structural_valid = all(checks);
if ~observed.structural_valid
    observed.failure_reason = 'shape, finiteness, or Time-axis check failed';
end
end

function verify_written_workbook(path, headers, expectedData, expected)
assert(isfile(path), 'EXP3:WorkbookMissing', 'Workbook was not written.');
sheets = sheetnames(path);
assert(isscalar(sheets) && string(sheets(1)) == string(expected.worksheet), ...
    'EXP3:WorksheetMismatch', 'Workbook worksheet mismatch.');
observedHeaders = readcell(path, 'Sheet', char(expected.worksheet), ...
    'Range', 'A1:BB1');
assert(isequal(observedHeaders, headers), 'EXP3:HeaderMismatch', ...
    'Workbook headers mismatch.');
observedData = readmatrix(path, 'Sheet', char(expected.worksheet), ...
    'Range', 'A2:BB3002');
assert(isequal(observedData, expectedData), 'EXP3:WorkbookRoundTripMismatch', ...
    'Workbook numeric content differs after write/read round trip.');
end

function append_attempt_record(path, log, record)
if isempty(log.attempts)
    log.attempts = record;
else
    log.attempts(end + 1) = record;
end
parent = fileparts(path);
if ~isfolder(parent)
    mkdir(parent);
end
temporaryPath = [path '.tmp'];
assert(~isfile(temporaryPath), 'EXP3:AttemptLogTempExists', ...
    'Refusing to overwrite stale attempt-log temporary file.');
fid = fopen(temporaryPath, 'w');
assert(fid ~= -1, 'EXP3:AttemptLogOpen', 'Could not open attempt-log temp file.');
cleanupFile = onCleanup(@() fclose_if_open(fid));
fprintf(fid, '%s\n', jsonencode(log, 'PrettyPrint', true, ...
    'ConvertInfAndNaN', true));
fclose(fid);
clear cleanupFile;
movefile(temporaryPath, path, 'f');
end

function timestamp = utc_timestamp()
value = datetime('now', 'TimeZone', 'UTC', ...
    'Format', "yyyy-MM-dd'T'HH:mm:ss.SSSXXX");
timestamp = char(string(value));
end

function digestHex = sha256_file(path)
assert(isfile(path), 'EXP3:HashInputMissing', 'Missing hash input: %s', path);
fid = fopen(path, 'rb');
assert(fid ~= -1, 'EXP3:HashInputOpen', 'Could not open hash input: %s', path);
cleanup = onCleanup(@() fclose_if_open(fid));
bytes = fread(fid, Inf, 'uint8=>uint8');
digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(bytes);
raw = typecast(digest.digest(), 'uint8');
digestHex = lower(reshape(dec2hex(raw, 2).', 1, []));
end

function close_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end

function cleanup_environment(originalPath, originalDir, modelName)
close_if_loaded(modelName);
close_if_loaded('TElib');
close_if_loaded('tesys');
path(originalPath);
cd(originalDir);
end

function fclose_if_open(fid)
if fid ~= -1
    try
        fclose(fid);
    catch
    end
end
end
