function result = test_exp3_hotfix_manifest_contract()
%TEST_EXP3_HOTFIX_MANIFEST_CONTRACT Validate generator/manifest fields without sim.

scriptDir = fileparts([mfilename('fullpath') '.m']);
generatorPath = fullfile(scriptDir, 'generate_exp3_heldout.m');
manifestPath = fullfile(scriptDir, 'EXP3_POST_FREEZE_HOTFIX_003.json');

source = fileread(generatorPath);
manifest = jsondecode(fileread(manifestPath));

tokens = regexp(source, ...
    'hotfixManifest\.([A-Za-z0-9_]+)', 'tokens');
required = unique(cellfun(@(x) x{1}, tokens, ...
    'UniformOutput', false));
missing = setdiff(required, fieldnames(manifest));

assert(isempty(missing), 'EXP3:HotfixManifestContract', ...
    'Manifest is missing generator-required fields: %s', ...
    strjoin(missing, ', '));

assert(strcmp(manifest.hotfix_id, ...
    'EXP3_POST_FREEZE_HOTFIX_003'), ...
    'EXP3:HotfixManifestIdentity', ...
    'Unexpected hotfix manifest identity.');

assert(strcmp(manifest.status, ...
    'AUTHORIZED_BEFORE_REPLACEMENT_ATTEMPT'), ...
    'EXP3:HotfixManifestStatus', ...
    'Unexpected hotfix manifest status.');

result = true;
fprintf(['PASS: generator/hotfix manifest contract complete; ' ...
    'sim not called.\n']);
end