function result = test_exp3_runtime_provenance()
%TEST_EXP3_RUNTIME_PROVENANCE Validate exact runtime field semantics only.
%
% This regression test queries version metadata and exercises the fail-closed
% runtime gate. It does not load the simulator, call sim, or consume a run RNG.

expected = struct( ...
    'matlab_version_full', '25.2.0.3312555 (R2025b) Update 6', ...
    'matlab_release', '2025b', ...
    'matlab_build', '3312555', ...
    'matlab_product_date', '28-Jul-2025', ...
    'matlab_runtime_update_date', 'June 30, 2026', ...
    'simulink_version', '25.2', ...
    'simulink_release', '(R2025b)', ...
    'simulink_product_date', '28-Jul-2025', ...
    'architecture', 'MACA64', ...
    'matlabroot', '/Applications/MATLAB_R2025b.app');

actual = capture_runtime();
assert_runtime(actual, expected);
assert_identifier(@() assert_runtime(with_field(actual, ...
    'matlab_product_date', 'wrong'), expected), ...
    'EXP3:MatlabProductDateMismatch');
assert_identifier(@() assert_runtime(with_field(actual, ...
    'matlab_build', 'wrong'), expected), 'EXP3:MatlabBuildMismatch');
assert_identifier(@() assert_runtime(with_field(actual, ...
    'matlab_release', 'wrong'), expected), 'EXP3:MatlabReleaseMismatch');
assert_identifier(@() assert_runtime(with_field(actual, ...
    'matlab_version_full', 'wrong'), expected), ...
    'EXP3:MatlabVersionMismatch');
assert_identifier(@() assert_runtime(with_field(actual, ...
    'matlab_runtime_update_date', 'wrong'), expected), ...
    'EXP3:MatlabRuntimeUpdateDateMismatch');

result = true;
fprintf(['PASS: exact runtime accepted; wrong product date, build, release, ' ...
    'full version, and runtime/update date rejected.\n']);
end

function changed = with_field(value, field, replacement)
changed = value;
changed.(field) = replacement;
end

function assert_identifier(operation, expectedIdentifier)
observed = '';
try
    operation();
catch exception
    observed = exception.identifier;
end
assert(strcmp(observed, expectedIdentifier), 'EXP3:RegressionIdentifier', ...
    'Expected %s, observed %s.', expectedIdentifier, observed);
end

function runtime = capture_runtime()
matlabProduct = ver('MATLAB'); %#ok<VERMATLAB>
simulinkProduct = ver('Simulink');
exactVersion = version;
buildToken = regexp(exactVersion, '\.(\d+) \(R\d{4}[ab]\)', 'tokens', 'once');
assert(~isempty(buildToken), 'EXP3:MatlabBuildUnavailable', ...
    'Could not parse MATLAB build from version string.');
runtime = struct( ...
    'matlab_version_full', exactVersion, ...
    'matlab_release', version('-release'), ...
    'matlab_build', buildToken{1}, ...
    'matlab_product_date', matlabProduct.Date, ...
    'matlab_runtime_update_date', version('-date'), ...
    'simulink_version', simulinkProduct.Version, ...
    'simulink_release', simulinkProduct.Release, ...
    'simulink_product_date', simulinkProduct.Date, ...
    'architecture', computer, ...
    'matlabroot', matlabroot);
end

function assert_runtime(actual, expected)
assert(strcmp(actual.matlab_version_full, expected.matlab_version_full), ...
    'EXP3:MatlabVersionMismatch', 'MATLAB exact version mismatch.');
assert(strcmp(actual.matlab_release, expected.matlab_release), ...
    'EXP3:MatlabReleaseMismatch', 'MATLAB release mismatch.');
assert(strcmp(actual.matlab_build, expected.matlab_build), ...
    'EXP3:MatlabBuildMismatch', 'MATLAB build mismatch.');
assert(strcmp(actual.matlab_product_date, expected.matlab_product_date), ...
    'EXP3:MatlabProductDateMismatch', 'MATLAB product date mismatch.');
assert(strcmp(actual.matlab_runtime_update_date, ...
    expected.matlab_runtime_update_date), ...
    'EXP3:MatlabRuntimeUpdateDateMismatch', ...
    'MATLAB runtime/update date mismatch.');
assert(strcmp(actual.simulink_version, expected.simulink_version), ...
    'EXP3:SimulinkVersionMismatch', 'Simulink version mismatch.');
assert(strcmp(actual.simulink_release, expected.simulink_release), ...
    'EXP3:SimulinkReleaseMismatch', 'Simulink release mismatch.');
assert(strcmp(actual.simulink_product_date, expected.simulink_product_date), ...
    'EXP3:SimulinkDateMismatch', 'Simulink product date mismatch.');
assert(strcmp(actual.architecture, expected.architecture), ...
    'EXP3:ArchitectureMismatch', 'Architecture mismatch.');
assert(strcmp(actual.matlabroot, expected.matlabroot), ...
    'EXP3:MatlabRootMismatch', 'matlabroot mismatch.');
end
